# vim: set noet ts=4 sw=4:
# =============================================================================
# Libellus Potionis - Privacy-Friendly Alcohol Tracker
# Copyright (c) 2026 Martin A. Godisch <martin@godisch.de>
# =============================================================================
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <https://www.gnu.org/licenses/>.
#
# In addition, as permitted by section 7 of the GNU General Public License,
# this program may carry additional permissions; any such permissions that
# apply to it are stated in the accompanying COPYING.md file.
#
# =============================================================================
#  Makefile -- Libellus Potionis build tooling (repository root)
# =============================================================================
#
#  This is the ROOT orchestrator. It owns repository-wide concerns and delegates
#  each platform's build to that platform's own Makefile:
#
#      make -C android <target>     the Android build (Gradle)
#      make -C ios     <target>     the iOS build (XcodeGen / xcodebuild)
#
#  The tooling is being rebuilt one target group at a time. THIS revision defines
#  the HOUSEKEEPING targets only; the other groups (build, test, store assets,
#  publishing, checks) are added in later steps. The previous, monolithic Makefile
#  is preserved verbatim under attic/ as a reference while the rebuild proceeds.
#
#  TARGETS IN THIS REVISION
#    help               (default) print this list and do nothing else
#    clean              build OUTPUT of BOTH platforms (fans out)
#    distclean          clean + generated sources of BOTH platforms (fans out)
#    clean-android      Android build output only
#    distclean-android  Android build output + generated sources
#    clean-ios          iOS build output only
#    distclean-ios      iOS build output + generated sources
# =============================================================================

# =============================================================================
# CONFIGURATION
# =============================================================================

# GNU Make version guard -- see make/guard.mk. Included FIRST so a Make that is
# too old to honor the .ONESHELL/.SHELLFLAGS settings below aborts with a legible
# message before any of them (silently ignored on such a Make) can take effect.
include make/guard.mk

# Run each recipe in ONE bash process with strict error handling. The same three
# lines head all three Makefiles so a recipe behaves identically wherever it runs:
#   .ONESHELL       -- the whole recipe is a single shell invocation, so
#                      `set -euo pipefail` (below) governs every line of it.
#   .SHELLFLAGS -eu -o pipefail -c
#                   -- -e aborts on the first failing command, -u on an unset
#                      variable, -o pipefail on any failure inside a pipeline.
SHELL       := /bin/bash
.SHELLFLAGS := -eu -o pipefail -c
.ONESHELL:

# A bare `make` in a two-platform repository must not silently build one of them,
# so the default goal only prints the target list and changes nothing.
.DEFAULT_GOAL := help

help:
	@echo "Libellus Potionis -- repository build tooling"
	@echo
	@echo "Housekeeping (this revision):"
	@echo "  make clean              clear both platforms' build output"
	@echo "  make distclean          clear build output + generated sources (fresh-clone state)"
	@echo "  make clean-android      Android build output only"
	@echo "  make distclean-android  Android build output + generated sources"
	@echo "  make clean-ios          iOS build output only"
	@echo "  make distclean-ios      iOS build output + generated sources"
	@echo
	@echo "None of these touch releases/ -- staged release artifacts are removed by hand."

# =============================================================================
# HOUSEKEEPING
# =============================================================================
#
# The naming split follows the repository convention: each per-platform CHILD
# Makefile exposes a bare `clean`/`distclean` (it knows only its own platform),
# while the ROOT disambiguates with a -android/-ios suffix. The two verbs mean the
# same thing on both sides:
#   clean      -- build OUTPUT: regenerated by the next build, costs only time.
#   distclean  -- clean, plus the GENERATED SOURCES a build needs before it can
#                 start, i.e. back to a fresh-clone state.
#
# What NONE of them touch is releases/: those are staged, possibly already
# published artifacts. Clearing them is a deliberate act, never a side effect of
# housekeeping -- remove them by hand when you mean it.

# Aggregate: fan out to BOTH platforms. This is honest only now that iOS has a
# Makefile of its own: the previous root deliberately had no bare `clean`, because
# back then it would have cleaned Android and left the entire iOS tree standing --
# a name that promised twice what it delivered.
clean: clean-android clean-ios

distclean: distclean-android distclean-ios

clean-android:
	$(MAKE) -C android clean

distclean-android:
	$(MAKE) -C android distclean

clean-ios:
	$(MAKE) -C ios clean

distclean-ios:
	$(MAKE) -C ios distclean

.PHONY: help clean distclean clean-android distclean-android clean-ios distclean-ios
