/* vim: set et ts=4:
 * =============================================================================
 * Libellus Potionis - Privacy-Friendly Alcohol Tracker
 * Copyright (c) 2026 Martin A. Godisch <martin@godisch.de>
 * =============================================================================
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * In addition, as permitted by section 7 of the GNU General Public License,
 * this program may carry additional permissions; any such permissions that
 * apply to it are stated in the accompanying COPYING.md file.
 *
 * =============================================================================
 */
package de.godisch.potillus.data.security

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import androidx.annotation.VisibleForTesting
import java.security.GeneralSecurityException
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * A tiny envelope-encryption primitive backed by the Android Keystore.
 *
 * ────────────────────────────────────────────────────────────────────────────
 * WHY THIS CLASS EXISTS
 * ────────────────────────────────────────────────────────────────────────────
 * The app needs to protect one small secret at rest:
 *
 *   the serialised user-preferences bytes       (see AppPreferences)
 *
 * It formerly also sealed the 32-byte SQLCipher database passphrase, but
 * SQLCipher was removed in v0.73.0, so the preferences DataStore is now the sole
 * user. The preferences path always used the Android Keystore directly; the
 * earlier database-passphrase path had used the Jetpack
 * `androidx.security:security-crypto` library (`MasterKey` +
 * `EncryptedSharedPreferences`). Google **deprecated** that library in April 2025
 * (v1.1.0-alpha07) in favour of using the Android Keystore directly. So the code
 * base had two ways of doing the same thing, one of them deprecated.
 *
 * This class unifies everything onto a single, auditable primitive built only on
 * platform APIs, and the deprecated dependency is removed entirely.
 *
 * ────────────────────────────────────────────────────────────────────────────
 * WHAT "ENVELOPE ENCRYPTION" MEANS HERE
 * ────────────────────────────────────────────────────────────────────────────
 * A symmetric AES-256-GCM key is generated **inside** the Android Keystore
 * under [keyAlias] and never leaves it — on every CDD-compliant device the key
 * material lives in the TEE-backed Keystore. That is a platform requirement,
 * not something this class verifies: an emulator or a non-compliant build may
 * keep the key in software, and nothing here probes `KeyInfo.securityLevel`
 * for it. Note that it is NOT StrongBox-backed even on devices that have a StrongBox
 * secure element: that would require `setIsStrongBoxBacked(true)` at key
 * generation, which this class deliberately does not request — StrongBox is
 * absent on most devices, so requesting it needs an availability-probe /
 * fallback dance, and the TEE Keystore already meets this secret's threat
 * model (protecting a preferences blob at rest). We use that key to encrypt
 * ("seal") the secret and
 * store only the resulting ciphertext. To use the secret again we ask the
 * Keystore to decrypt ("open") it. The plaintext secret therefore exists only
 * transiently in process memory and is never written to disk.
 *
 * ────────────────────────────────────────────────────────────────────────────
 * ON-DISK / WIRE FORMAT
 * ────────────────────────────────────────────────────────────────────────────
 *     ┌─────────────── 12 bytes ───────────────┬──── variable ────┐
 *     │  GCM initialisation vector (IV / nonce) │ ciphertext + tag │
 *     └─────────────────────────────────────────┴──────────────────┘
 *
 * A FRESH random IV is generated by the Keystore on every [seal] call, so
 * encrypting the same plaintext twice yields different output (semantic
 * security). The 128-bit GCM authentication tag is appended to the ciphertext
 * by the cipher, so [open] automatically rejects any tampering by throwing.
 *
 * ────────────────────────────────────────────────────────────────────────────
 * THREADING
 * ────────────────────────────────────────────────────────────────────────────
 * [seal] and [open] are plain, synchronous, CPU-bound functions. They do NOT
 * switch dispatchers themselves — the caller decides; AppPreferences, the sole
 * user, wraps them in `withContext(Dispatchers.Default)`.
 *
 * Concurrent FIRST use is made safe HERE, not by the caller: [getOrCreateKey]
 * is a `containsAlias` followed by a `generateKey`, two separate Keystore
 * operations with no atomic check-and-create between them, and a second
 * generation under the same alias would replace the first key and leave
 * anything already sealed under it unreadable. The method is therefore
 * `@Synchronized` on this instance. (An earlier comment argued that DataStore
 * serialises `readFrom` and `writeTo` under one writer; whether that holds for
 * the `data` flow's reads is not something this class should depend on.) Two
 * INSTANCES on the same alias are still not protected against each other, so a
 * second consumer must share this instance rather than construct its own.
 *
 * @param keyAlias The Android Keystore alias under which this store's AES-256-GCM
 *                 key is generated and looked up. One alias per secret, so a
 *                 secret can be rotated on its own; today the preferences blob
 *                 is the only one.
 */
class KeystoreSecretStore(private val keyAlias: String) {

    /**
     * Encrypts [plaintext] and returns the self-describing blob `IV || ciphertext+tag`.
     *
     * @param plaintext The secret bytes to protect.
     * @return A byte array safe to persist anywhere (it reveals nothing
     *                  without the Keystore key).
     */
    fun seal(plaintext: ByteArray): ByteArray = sealWithKey(getOrCreateKey(), plaintext)

    /**
     * Decrypts a blob previously produced by [seal].
     *
     * @param blob The `IV || ciphertext+tag` byte array.
     * @return The original plaintext.
     * @throws java.security.GeneralSecurityException if [blob] is malformed, was
     *         tampered with (GCM tag mismatch), or the Keystore key that sealed it
     *         is gone (a Keystore wiped or corrupted by an OS update, say — a
     *         factory reset takes the file with it). In that last case
     *         [getOrCreateKey] has already generated a NEW key under the alias
     *         before the decryption fails, so the next [seal] writes under it.
     *         Callers decide how to react; AppPreferences maps this to a
     *         DataStore CorruptionException so the `ReplaceFileCorruptionHandler`
     *         resets the file to its defaults.
     */
    fun open(blob: ByteArray): ByteArray = openWithKey(getOrCreateKey(), blob)

    // ── Testable seam ─────────────────────────────────────────────────────────
    // The Android Keystore is unavailable on the plain JVM, so the pure cipher
    // logic is factored into key-injecting variants. Unit tests pass an ordinary
    // software AES-256 key to exercise the IV framing, round-trip and tamper
    // detection without a device (see KeystoreSecretStoreTest).

    /**
     * Encrypts [plaintext] under the supplied [key] and frames the result as
     * `IV || ciphertext+tag`. Used by [seal]; exposed for testing.
     */
    @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
    internal fun sealWithKey(key: SecretKey, plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(AES_GCM).apply { init(Cipher.ENCRYPT_MODE, key) }
        val iv = cipher.iv // 12-byte IV chosen by the provider
        val ciphertext = cipher.doFinal(plaintext)
        return iv + ciphertext // IV || ciphertext+tag
    }

    /**
     * Reverses [sealWithKey]: parses `IV || ciphertext+tag` and decrypts under
     * [key]. Used by [open]; exposed for testing.
     *
     * @throws java.security.GeneralSecurityException if [blob] is too short to
     *         contain an IV, or (as [javax.crypto.AEADBadTagException]) if the
     *         data was modified. Truncation deliberately maps to
     *         `GeneralSecurityException` rather than the `require`-style
     *         `IllegalArgumentException`: [open]'s public contract promises GSE
     *         for ANY malformed blob, and AppPreferences relies on that promise
     *         to translate decryption failures into a DataStore
     *         `CorruptionException` so the `ReplaceFileCorruptionHandler` can
     *         reset the file. An `IllegalArgumentException` would bypass that
     *         catch and crash the read instead of self-healing — a truncated
     *         (partially written / corrupted) preferences file is exactly the
     *         corruption case the handler exists for.
     */
    @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
    internal fun openWithKey(key: SecretKey, blob: ByteArray): ByteArray {
        if (blob.size < GCM_IV_LEN) {
            throw GeneralSecurityException("Sealed blob too short to contain an IV")
        }
        val iv = blob.copyOfRange(0, GCM_IV_LEN)
        val ciphertext = blob.copyOfRange(GCM_IV_LEN, blob.size)
        val cipher = Cipher.getInstance(AES_GCM).apply {
            init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(GCM_TAG_BITS, iv))
        }
        return cipher.doFinal(ciphertext)
    }

    /**
     * Returns the AES-256-GCM key for [keyAlias] from the Android Keystore,
     * generating it on first use.
     *
     * The key is NOT created with `setUserAuthenticationRequired(true)`: that
     * would demand biometric/credential confirmation on every read, which is far
     * too aggressive for secrets read during normal app startup and navigation.
     * Protection relies on the Keystore's own device-unlock policy and the
     * hardware backing of the key.
     *
     * `@Synchronized` so that two callers cannot both miss `containsAlias` and
     * both generate (see THREADING in the class comment).
     */
    @Synchronized
    private fun getOrCreateKey(): SecretKey {
        val ks = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        if (!ks.containsAlias(keyAlias)) {
            KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE).apply {
                init(
                    KeyGenParameterSpec.Builder(
                        keyAlias,
                        KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
                    )
                        .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                        .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                        .setKeySize(256)
                        .setRandomizedEncryptionRequired(true) // forces a fresh IV per encryption
                        .build(),
                )
            }.generateKey()
        }
        return ks.getKey(keyAlias, null) as SecretKey
    }

    companion object {
        /** Android Keystore provider name. */
        private const val ANDROID_KEYSTORE = "AndroidKeyStore"

        /** AES in Galois/Counter Mode; GCM provides confidentiality + integrity (AEAD). */
        private const val AES_GCM = "AES/GCM/NoPadding"

        /** 96-bit IV — the size recommended by NIST SP 800-38D for GCM. */
        private const val GCM_IV_LEN = 12

        /** 128-bit authentication tag — the maximum (and strongest) GCM tag length. */
        private const val GCM_TAG_BITS = 128
    }
}
