/* vim: set et ts=4:
 * =============================================================================
 * Libellus Potionis - Privacy-Friendly Alcohol Tracker
 * Copyright (c) 2026 Martin A. Godisch <android@godisch.de>
 * =============================================================================
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * =============================================================================
 */
package de.godisch.potillus.data.security

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import androidx.annotation.VisibleForTesting
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * A tiny envelope-encryption primitive backed by the Android Keystore.
 *
 * ────────────────────────────────────────────────────────────────────────────
 * WHY THIS CLASS EXISTS
 * ────────────────────────────────────────────────────────────────────────────
 * The app needs to protect one small secret at rest:
 *
 *   the serialised user-preferences bytes       (see AppPreferences)
 *
 * It formerly also sealed the 32-byte SQLCipher database passphrase, but
 * SQLCipher was removed in v0.73.0, so the preferences DataStore is now the sole
 * user. The preferences path always used the Android Keystore directly; the
 * earlier database-passphrase path had used the Jetpack
 * `androidx.security:security-crypto` library (`MasterKey` +
 * `EncryptedSharedPreferences`). Google **deprecated** that library in April 2025
 * (v1.1.0-alpha07) in favour of using the Android Keystore directly. So the code
 * base had two ways of doing the same thing, one of them deprecated.
 *
 * This class unifies everything onto a single, auditable primitive built only on
 * platform APIs, and the deprecated dependency is removed entirely.
 *
 * ────────────────────────────────────────────────────────────────────────────
 * WHAT "ENVELOPE ENCRYPTION" MEANS HERE
 * ────────────────────────────────────────────────────────────────────────────
 * A symmetric AES-256-GCM key is generated **inside** the Android Keystore
 * under [keyAlias] and never leaves it — on devices with a StrongBox secure
 * element the key material stays in dedicated hardware; otherwise it lives in
 * the TEE-backed Keystore. We use that key to encrypt ("seal") the secret and
 * store only the resulting ciphertext. To use the secret again we ask the
 * Keystore to decrypt ("open") it. The plaintext secret therefore exists only
 * transiently in process memory and is never written to disk.
 *
 * ────────────────────────────────────────────────────────────────────────────
 * ON-DISK / WIRE FORMAT
 * ────────────────────────────────────────────────────────────────────────────
 *     ┌─────────────── 12 bytes ───────────────┬──── variable ────┐
 *     │  GCM initialisation vector (IV / nonce) │ ciphertext + tag │
 *     └─────────────────────────────────────────┴──────────────────┘
 *
 * A FRESH random IV is generated by the Keystore on every [seal] call, so
 * encrypting the same plaintext twice yields different output (semantic
 * security). The 128-bit GCM authentication tag is appended to the ciphertext
 * by the cipher, so [open] automatically rejects any tampering by throwing.
 *
 * ────────────────────────────────────────────────────────────────────────────
 * THREADING
 * ────────────────────────────────────────────────────────────────────────────
 * [seal] and [open] are plain, synchronous, CPU-bound functions. They do NOT
 * switch dispatchers themselves — the caller decides (e.g. AppPreferences wraps
 * them in `withContext(Dispatchers.Default)`; AppDatabase calls them once during
 * cold start). Keystore key lookup/creation is internally serialised by the
 * platform, so concurrent first-use is safe.
 *
 * @param keyAlias The Android Keystore alias under which this store's AES-256-GCM
 *                 key is generated and looked up. Use a DISTINCT alias per secret
 *                 so the two secrets can be rotated independently.
 */
class KeystoreSecretStore(private val keyAlias: String) {

    /**
     * Encrypts [plaintext] and returns the self-describing blob `IV || ciphertext+tag`.
     *
     * @param plaintext The secret bytes to protect.
     * @return          A byte array safe to persist anywhere (it reveals nothing
     *                  without the Keystore key).
     */
    fun seal(plaintext: ByteArray): ByteArray = sealWithKey(getOrCreateKey(), plaintext)

    /**
     * Decrypts a blob previously produced by [seal].
     *
     * @param blob The `IV || ciphertext+tag` byte array.
     * @return     The original plaintext.
     * @throws java.security.GeneralSecurityException if [blob] is malformed, was
     *         tampered with (GCM tag mismatch), or the Keystore key is missing
     *         (e.g. after a factory reset). Callers decide how to react — e.g.
     *         AppPreferences maps this to a DataStore CorruptionException and
     *         resets the file; AppDatabase treats it as an unrecoverable DB.
     */
    fun open(blob: ByteArray): ByteArray = openWithKey(getOrCreateKey(), blob)

    // ── Testable seam ─────────────────────────────────────────────────────────
    // The Android Keystore is unavailable on the plain JVM, so the pure cipher
    // logic is factored into key-injecting variants. Unit tests pass an ordinary
    // software AES-256 key to exercise the IV framing, round-trip and tamper
    // detection without a device (see KeystoreSecretStoreTest).

    /**
     * Encrypts [plaintext] under the supplied [key] and frames the result as
     * `IV || ciphertext+tag`. Used by [seal]; exposed for testing.
     */
    @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
    internal fun sealWithKey(key: SecretKey, plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(AES_GCM).apply { init(Cipher.ENCRYPT_MODE, key) }
        val iv         = cipher.iv                       // 12-byte IV chosen by the provider
        val ciphertext = cipher.doFinal(plaintext)
        return iv + ciphertext                           // IV || ciphertext+tag
    }

    /**
     * Reverses [sealWithKey]: parses `IV || ciphertext+tag` and decrypts under
     * [key]. Used by [open]; exposed for testing.
     *
     * @throws javax.crypto.AEADBadTagException (a GeneralSecurityException) if the
     *         data was modified, or [IllegalArgumentException] if [blob] is too
     *         short to contain an IV.
     */
    @VisibleForTesting(otherwise = VisibleForTesting.PRIVATE)
    internal fun openWithKey(key: SecretKey, blob: ByteArray): ByteArray {
        require(blob.size >= GCM_IV_LEN) { "Sealed blob too short to contain an IV" }
        val iv         = blob.copyOfRange(0, GCM_IV_LEN)
        val ciphertext = blob.copyOfRange(GCM_IV_LEN, blob.size)
        val cipher = Cipher.getInstance(AES_GCM).apply {
            init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(GCM_TAG_BITS, iv))
        }
        return cipher.doFinal(ciphertext)
    }

    /**
     * Returns the AES-256-GCM key for [keyAlias] from the Android Keystore,
     * generating it on first use.
     *
     * The key is NOT created with `setUserAuthenticationRequired(true)`: that
     * would demand biometric/credential confirmation on every read, which is far
     * too aggressive for secrets read during normal app startup and navigation.
     * Protection relies on the Keystore's own device-unlock policy and the
     * hardware backing of the key.
     */
    private fun getOrCreateKey(): SecretKey {
        val ks = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        if (!ks.containsAlias(keyAlias)) {
            KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE).apply {
                init(
                    KeyGenParameterSpec.Builder(
                        keyAlias,
                        KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
                    )
                        .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                        .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                        .setKeySize(256)
                        .setRandomizedEncryptionRequired(true)   // forces a fresh IV per encryption
                        .build()
                )
            }.generateKey()
        }
        return ks.getKey(keyAlias, null) as SecretKey
    }

    companion object {
        /** Android Keystore provider name. */
        private const val ANDROID_KEYSTORE = "AndroidKeyStore"

        /** AES in Galois/Counter Mode; GCM provides confidentiality + integrity (AEAD). */
        private const val AES_GCM      = "AES/GCM/NoPadding"

        /** 96-bit IV — the size recommended by NIST SP 800-38D for GCM. */
        private const val GCM_IV_LEN   = 12

        /** 128-bit authentication tag — the maximum (and strongest) GCM tag length. */
        private const val GCM_TAG_BITS = 128
    }
}
