/* vim: set et ts=4:
 * =============================================================================
 * Libellus Potionis "Potillus" -- Privacy-Friendly Alcohol Tracker
 * Copyright (c) 2026 Martin A. Godisch <android@godisch.de>
 * =============================================================================
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * =============================================================================
 */
package de.godisch.potillus.data.repository

// =============================================================================
// BackupRepository.kt – Transactional backup import
// =============================================================================
//
// This repository owns the database transaction that spans the `entries` and
// `drinks` tables during a backup import. It uses DAOs directly (rather than
// domain repositories) for two reasons:
//
//   1. TRANSACTIONS: Room's withTransaction requires operations on a single
//      database connection/executor. IEntryRepository.add() and
//      IDrinkRepository.add() are suspend functions backed by DAOs on the
//      same connection, so they are safe inside a transaction. However,
//      IDrinkRepository.drinks (a Flow) cannot be collected inside a
//      transaction – hence the dedicated DrinkDao.getAllOnce() one-shot query.
//
//   2. ENTITY CONVERSION: toDomain()/toEntity() are private extension functions
//      in their respective repository files. Re-declaring them here as private
//      helpers (two one-liners) is the minimal, self-contained approach that
//      avoids making those functions public or creating a shared conversion
//      module.
//
// ID REMAPPING RATIONALE:
//   Backup drink IDs are auto-generated by the source device's database and
//   differ from this device's IDs. Before inserting entries, we build an
//   idMap[backupId → localId] so that entries correctly reference the local
//   drinks. Name-matching is used as a heuristic deduplication key: if a drink
//   with the same name already exists locally (e.g. a preset), its ID is
//   reused rather than creating a duplicate.
// =============================================================================

import androidx.room.withTransaction
import de.godisch.potillus.data.db.AppDatabase
import de.godisch.potillus.data.db.dao.DrinkDao
import de.godisch.potillus.data.db.dao.EntryDao
import de.godisch.potillus.data.db.entity.DrinkEntity
import de.godisch.potillus.data.db.entity.EntryEntity
import de.godisch.potillus.domain.model.ConsumptionEntry
import de.godisch.potillus.domain.model.DrinkCategory
import de.godisch.potillus.domain.model.DrinkDefinition

class BackupRepository(
    private val entryDao: EntryDao,
    private val drinkDao: DrinkDao,
    private val db:       AppDatabase
) : IBackupRepository {

    /**
     * REPLACE import: wipes all entries and user-created drinks, then inserts the
     * backup. Preset drinks are kept and matched by name so backup entries relink
     * to the existing preset ids. Runs in a single transaction (all-or-nothing).
     *
     * @param backupDrinks  Drinks from the backup file.
     * @param backupEntries Entries from the backup file.
     * @return              [ImportStats] with the number of imported entries (skipped = 0).
     */
    override suspend fun importReplace(
        backupDrinks:  List<DrinkDefinition>,
        backupEntries: List<ConsumptionEntry>
    ): ImportStats {
        var imported = 0
        db.withTransaction {
            entryDao.deleteAll()
            drinkDao.deleteUserCreatedDrinks()

            // Build the name → id map INSIDE the transaction, AFTER the
            // deletes, so it reflects only the rows that actually survive (the
            // presets). A getAllOnce() one-shot suspend query is transaction-safe
            // (unlike collecting the getAll() Flow).
            //
            // WHY this ordering matters:
            //   If the map is captured BEFORE deleteUserCreatedDrinks(), it still
            //   contains the deleted user drinks. buildIdMap() would then map a
            //   backup drink whose name equals a just-deleted user drink to that
            //   drink's OLD (now non-existent) id, instead of re-inserting it. The
            //   subsequent entry insert would reference a missing parent row and
            //   trip the entries→drinks FOREIGN KEY (RESTRICT) constraint, rolling
            //   back the whole import. That scenario is common: re-importing your
            //   own backup over a database that still holds the matching user
            //   drinks. Capturing the map post-delete makes such names re-insert
            //   with a fresh id, so the FK is always satisfied.
            val existingByName = drinkDao.getAllOnce().associate { it.name to it.id }

            val idMap = buildIdMap(backupDrinks, existingByName)

            backupEntries.forEach { entry ->
                // Use insertOrReplace (REPLACE strategy) here because backup
                // entries are re-inserted with id=0 (remapped), which means Room will
                // auto-generate a fresh primary key anyway. REPLACE is semantically
                // correct for the restore scenario and is kept here for clarity; the
                // normal insert path uses ABORT to catch unintended collisions.
                val remapped = entry.copy(id = 0, drinkId = idMap[entry.drinkId] ?: entry.drinkId)
                entryDao.insertOrReplace(remapped.toEntity())
                imported++
            }
        }
        return ImportStats(imported, skipped = 0)
    }

    /**
     * MERGE import: keeps existing data and adds the backup, skipping entries that
     * duplicate an existing (timestamp, drink) pair. Runs in a single transaction.
     *
     * @param backupDrinks  Drinks from the backup file.
     * @param backupEntries Entries from the backup file.
     * @return              [ImportStats] with the imported and skipped counts.
     */
    override suspend fun importMerge(
        backupDrinks:  List<DrinkDefinition>,
        backupEntries: List<ConsumptionEntry>
    ): ImportStats {
        val existingByName = drinkDao.getAllOnce().associate { it.name to it.id }

        var imported = 0; var skipped = 0
        db.withTransaction {
            val idMap = buildIdMap(backupDrinks, existingByName)

            backupEntries.forEach { entry ->
                val remapped = entry.copy(id = 0, drinkId = idMap[entry.drinkId] ?: entry.drinkId)
                if (entryDao.countByTimestampAndDrink(remapped.timestampMillis, remapped.drinkId) > 0) {
                    skipped++
                } else {
                    // Same rationale as importReplace – entries are inserted
                    // with id=0 so REPLACE is equivalent to a normal insert here.
                    entryDao.insertOrReplace(remapped.toEntity())
                    imported++
                }
            }
        }
        return ImportStats(imported, skipped)
    }

    /**
     * Builds a map from backup drink ID → local database ID.
     *
     * For each backup drink:
     *   - If a drink with the same name already exists locally, reuse its ID.
     *   - Otherwise, insert the backup drink (with id=0 so Room auto-generates
     *     a new primary key) and record the returned ID.
     *
     * Must be called inside a `withTransaction` block.
     */
    private suspend fun buildIdMap(
        backupDrinks:  List<DrinkDefinition>,
        existingByName: Map<String, Long>
    ): Map<Long, Long> {
        val idMap = mutableMapOf<Long, Long>()
        backupDrinks.forEach { drink ->
            idMap[drink.id] = existingByName[drink.name]
                ?: drinkDao.insert(drink.copy(id = 0).toEntity())
        }
        return idMap
    }

    // ── Local entity conversion helpers ──────────────────────────────────────
    //
    // WHY duplicated here instead of reusing the private funs in DrinkRepository
    // / EntryRepository?
    //   Those conversion functions are file-private (`private fun`). Making them
    //   `internal` would expose them to the entire module. Re-declaring them as
    //   private helpers in this file is the least-invasive solution and keeps
    //   BackupRepository self-contained.

    /** Maps a domain [DrinkDefinition] to its Room [DrinkEntity] (category stored as enum name). */
    private fun DrinkDefinition.toEntity() = DrinkEntity(
        id             = id,
        name           = name,
        volumeMl       = volumeMl,
        alcoholPercent = alcoholPercent,
        isPreset       = isPreset,
        isFavorite     = isFavorite,
        category       = category.name
    )

    /** Maps a domain [ConsumptionEntry] to its Room [EntryEntity]. */
    private fun ConsumptionEntry.toEntity() = EntryEntity(
        id              = id,
        drinkId         = drinkId,
        drinkName       = drinkName,
        volumeMl        = volumeMl,
        alcoholPercent  = alcoholPercent,
        gramsAlcohol    = gramsAlcohol,
        timestampMillis = timestampMillis,
        logicalDate     = logicalDate,
        note            = note
    )
}
