/* vim: set et ts=4:
 * =============================================================================
 * Libellus Potionis - Privacy-Friendly Alcohol Tracker
 * Copyright (c) 2026 Martin A. Godisch <martin@godisch.de>
 * =============================================================================
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * In addition, as permitted by section 7 of the GNU General Public License,
 * this program may carry additional permissions; any such permissions that
 * apply to it are stated in the accompanying COPYING.md file.
 *
 * =============================================================================
 */
package de.godisch.potillus.data.repository

// =============================================================================
// BackupRepository.kt – Transactional backup import
// =============================================================================
//
// This repository owns the database transaction that spans the `entries` and
// `drinks` tables during a backup import. It uses DAOs directly (rather than
// domain repositories) for two reasons:
//
//   1. TRANSACTIONS: Room's withTransaction requires operations on a single
//      database connection/executor. IEntryRepository.add() and
//      IDrinkRepository.add() are suspend functions backed by DAOs on the
//      same connection, so they are safe inside a transaction. However,
//      IDrinkRepository.drinks (a Flow) cannot be collected inside a
//      transaction – hence the dedicated DrinkDao.getAllOnce() one-shot query.
//
//   2. ENTITY CONVERSION: toDomain()/toEntity() are `internal` extension
//      functions defined once in EntityMapping.kt and shared by every
//      repository (DrinkRepository, EntryRepository, BackupRepository). This
//      class reuses them directly rather than re-declaring its own private
//      copies, so a schema change is reflected in a single place (the previous
//      per-repository duplication was removed in the C-01 refactor).
//
// ID REMAPPING RATIONALE:
//   Backup drink IDs are auto-generated by the source device's database and
//   differ from this device's IDs. Before inserting entries, we build an
//   idMap[backupId → localId] so that entries correctly reference the local
//   drinks. Name-matching is used as a heuristic deduplication key: if a drink
//   with the same name already exists locally (e.g. a preset), its ID is
//   reused rather than creating a duplicate.
// =============================================================================

import androidx.room.withTransaction
import de.godisch.potillus.data.db.AppDatabase
import de.godisch.potillus.data.db.dao.DrinkDao
import de.godisch.potillus.data.db.dao.EntryDao
import de.godisch.potillus.domain.model.ConsumptionEntry
import de.godisch.potillus.domain.model.DrinkDefinition

class BackupRepository(
    private val entryDao: EntryDao,
    private val drinkDao: DrinkDao,
    private val db: AppDatabase,
) : IBackupRepository {

    /**
     * REPLACE import: wipes all entries and user-created drinks, then inserts the
     * backup. Preset drinks are kept and matched by name so backup entries relink
     * to the existing preset ids. Runs in a single transaction (all-or-nothing).
     *
     * @param backupDrinks  Drinks from the backup file.
     * @param backupEntries Entries from the backup file.
     * @return [ImportStats] with the number of imported entries (skipped = 0).
     */
    override suspend fun importReplace(
        backupDrinks: List<DrinkDefinition>,
        backupEntries: List<ConsumptionEntry>,
    ): ImportStats {
        var imported = 0
        db.withTransaction {
            entryDao.deleteAll()
            drinkDao.deleteUserCreatedDrinks()

            // Build the name → id map INSIDE the transaction, AFTER the
            // deletes, so it reflects only the rows that actually survive (the
            // presets). A getAllOnce() one-shot suspend query is transaction-safe
            // (unlike collecting the getAll() Flow).
            //
            // WHY this ordering matters:
            //   If the map is captured BEFORE deleteUserCreatedDrinks(), it still
            //   contains the deleted user drinks. buildIdMap() would then map a
            //   backup drink whose name equals a just-deleted user drink to that
            //   drink's OLD (now non-existent) id, instead of re-inserting it. The
            //   subsequent entry insert would reference a missing parent row and
            //   trip the entries→drinks FOREIGN KEY (RESTRICT) constraint, rolling
            //   back the whole import. That scenario is common: re-importing your
            //   own backup over a database that still holds the matching user
            //   drinks. Capturing the map post-delete makes such names re-insert
            //   with a fresh id, so the FK is always satisfied.
            val existingByName = drinkDao.getAllOnce().associate { it.name to it.id }

            val idMap = buildIdMap(backupDrinks, existingByName)

            backupEntries.forEach { entry ->
                // Use insertOrReplace (REPLACE strategy) here because backup
                // entries are re-inserted with id=0 (remapped), which means Room will
                // auto-generate a fresh primary key anyway. REPLACE is semantically
                // correct for the restore scenario and is kept here for clarity; the
                // normal insert path uses ABORT to catch unintended collisions.
                val remapped = entry.copy(id = 0, drinkId = requireMapped(idMap, entry.drinkId))
                entryDao.insertOrReplace(remapped.toEntity())
                imported++
            }
        }
        return ImportStats(imported, skipped = 0)
    }

    /**
     * MERGE import: keeps existing data and adds the backup, skipping entries that
     * duplicate an existing (timestamp, drink) pair. Runs in a single transaction.
     *
     * @param backupDrinks  Drinks from the backup file.
     * @param backupEntries Entries from the backup file.
     * @return [ImportStats] with the imported and skipped counts.
     */
    override suspend fun importMerge(
        backupDrinks: List<DrinkDefinition>,
        backupEntries: List<ConsumptionEntry>,
    ): ImportStats {
        var imported = 0
        var skipped = 0
        db.withTransaction {
            // Build the name → id map INSIDE the transaction (mirroring
            // importReplace), so this read is part of the same atomic unit as the
            // inserts below rather than a read-outside-write (TOCTOU) gap. MERGE
            // performs no deletes, so the precise timing matters less than it does
            // in REPLACE, but reading inside the transaction keeps the two import
            // paths consistent. getAllOnce() is a one-shot suspend query and is
            // therefore transaction-safe (unlike collecting the getAll() Flow).
            val existingByName = drinkDao.getAllOnce().associate { it.name to it.id }

            val idMap = buildIdMap(backupDrinks, existingByName)

            backupEntries.forEach { entry ->
                val remapped = entry.copy(id = 0, drinkId = requireMapped(idMap, entry.drinkId))
                if (entryDao.countByTimestampAndDrink(remapped.timestampMillis, remapped.drinkId) > 0) {
                    skipped++
                } else {
                    // Same rationale as importReplace – entries are inserted
                    // with id=0 so REPLACE is equivalent to a normal insert here.
                    entryDao.insertOrReplace(remapped.toEntity())
                    imported++
                }
            }
        }
        return ImportStats(imported, skipped)
    }

    /**
     * Builds a map from backup drink ID → local database ID.
     *
     * For each backup drink:
     *   - If a drink with the same name already exists locally, reuse its ID.
     *   - Otherwise, insert the backup drink (with id=0 so Room auto-generates
     *     a new primary key) and record the returned ID.
     *
     * A freshly inserted drink's name is added to a local, growing index so that a
     * SECOND backup drink sharing the same (not-yet-existing) name reuses the id
     * just inserted for the first one, instead of inserting a duplicate row with
     * the same name. Without this, a backup containing two identically named new
     * drinks would create two local drinks with that name.
     *
     * NOTE (catalogue merge): this inserts a new-named drink even when no entry
     * references it, so `importMerge` deliberately merges the backup's drink
     * catalogue — including custom drinks that carry no entries — not only the
     * consumption entries. That is the intended contract (see [IBackupRepository]);
     * it is idempotent, because a later merge re-matches the same name. If MERGE is
     * ever redefined as entries-only, insert lazily from the entry loop instead.
     *
     * Must be called inside a `withTransaction` block.
     */
    private suspend fun buildIdMap(
        backupDrinks: List<DrinkDefinition>,
        existingByName: Map<String, Long>,
    ): Map<Long, Long> {
        val idMap = mutableMapOf<Long, Long>()
        // Mutable copy of the existing name → id snapshot, grown as new drinks are
        // inserted so later same-named backup drinks reuse the fresh id (see KDoc).
        val nameToId = existingByName.toMutableMap()
        backupDrinks.forEach { drink ->
            val localId = nameToId[drink.name]
                ?: drinkDao.insert(drink.copy(id = 0).toEntity()).also { newId ->
                    nameToId[drink.name] = newId
                }
            idMap[drink.id] = localId
        }
        return idMap
    }

    /**
     * The local drink id [backupDrinkId] was remapped to — a STRICT lookup.
     *
     * Every entry that reaches the repository through [BackupManager.parseBackupJson]
     * is guaranteed to reference a drink from the same backup (its Guard 5), and
     * [buildIdMap] maps every backup drink, so this cannot fail on the production
     * path. The former silent fallback (`idMap[…] ?: entry.drinkId`) is exactly
     * what this replaces: for a caller that bypasses the parser, a dangling raw
     * backup id either collided with a local preset id — silently attaching the
     * entry to the WRONG drink — or tripped the entries→drinks FK deep inside the
     * transaction. Failing loudly here names the actual problem instead, and the
     * surrounding `withTransaction` still rolls everything back (v0.79.0 QA fix).
     */
    private fun requireMapped(idMap: Map<Long, Long>, backupDrinkId: Long): Long = requireNotNull(idMap[backupDrinkId]) {
        "backup entry references drinkId $backupDrinkId, which is not in the backup's drinks list"
    }

    // ── Entity conversion ─────────────────────────────────────────────────────
    //
    // DrinkDefinition.toEntity() and ConsumptionEntry.toEntity() are defined
    // as `internal` extension functions in EntityMapping.kt and are therefore
    // in scope here without any further declaration. The former private copies
    // in this class have been removed as part of the C-01 DRY fix.
}
