/* vim: set et ts=4:
 * =============================================================================
 * Libellus Potionis - Privacy-Friendly Alcohol Tracker
 * Copyright (c) 2026 Martin A. Godisch <martin@godisch.de>
 * =============================================================================
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * In addition, as permitted by section 7 of the GNU General Public License,
 * this program may carry additional permissions; any such permissions that
 * apply to it are stated in the accompanying COPYING.md file.
 *
 * =============================================================================
 */
package de.godisch.potillus.data.repository

// =============================================================================
// BackupRepository.kt – Transactional backup import
// =============================================================================
//
// This repository owns the database transaction that spans the `entries` and
// `drinks` tables during a backup import. It uses DAOs directly (rather than
// domain repositories) for two reasons:
//
//   1. TRANSACTIONS: Room's withTransaction requires operations on a single
//      database connection/executor. IEntryRepository.add() and
//      IDrinkRepository.add() are suspend functions backed by DAOs on the
//      same connection, so they are safe inside a transaction. However,
//      IDrinkRepository.drinks (a Flow) cannot be collected inside a
//      transaction – hence the dedicated DrinkDao.getAllOnce() one-shot query.
//
//   2. ENTITY CONVERSION: toDomain()/toEntity() are `internal` extension
//      functions defined once in EntityMapping.kt and shared by every
//      repository (DrinkRepository, EntryRepository, BackupRepository). This
//      class reuses them directly rather than re-declaring its own private
//      copies, so a schema change is reflected in a single place (the previous
//      per-repository duplication was removed in the C-01 refactor).
//
// ID REMAPPING RATIONALE:
//   Backup drink IDs are auto-generated by the source device's database and
//   differ from this device's IDs. Before inserting entries, we build an
//   idMap[backupId → localId] so that entries correctly reference the local
//   drinks. Name-matching is used as a heuristic deduplication key: if a drink
//   with the same name already exists locally (e.g. a preset), its ID is
//   reused rather than creating a duplicate.
// =============================================================================

import androidx.room.withTransaction
import de.godisch.potillus.data.db.AppDatabase
import de.godisch.potillus.data.db.dao.DrinkDao
import de.godisch.potillus.data.db.dao.EntryDao
import de.godisch.potillus.data.db.dao.LogicalDayKeyDao
import de.godisch.potillus.domain.model.ConsumptionEntry
import de.godisch.potillus.domain.model.DrinkDefinition

// =============================================================================
// WHAT AN IMPORT DOES TO THE DERIVED LOGICAL DAY
// =============================================================================
//
// This class writes rows into `entries` without deriving their day — it inserts
// what the file holds, remapped ids and all. That is exactly the situation the
// key in `logical_day_key` exists for, and the rule is stated once, here:
//
//   ANY PATH THAT INSERTS ROWS OR MOVES THEIR READING WITHOUT DERIVING THE DAY
//   INVALIDATES THE KEY.
//
// So both import modes end by setting it back to "not computed yet". The caller
// — `SettingsViewModel.applyImport` — then runs the realignment itself, which
// derives every day in the table under THIS device's boundary and is what makes
// a backup written under a different day-change time land on the days that hold
// here. It does not wait for the settings collector in `PotillusApp` to do it:
// a MERGE writes no setting, and neither does a REPLACE whose block matches what
// is stored, so no emission would follow (found in the v0.86.0 QA round).
//
// The one thing taken from the file's own boundary is the repair of pre-0.85.0
// calendar entries: it has to put a wall-clock time back onto the day the file
// names, and only the file's boundary says where that day started. Without the
// repair an old backup would import precisely the damage the realignment
// removes from local rows.
// =============================================================================

class BackupRepository(
    private val entryDao: EntryDao,
    private val drinkDao: DrinkDao,
    private val keyDao: LogicalDayKeyDao,
    private val db: AppDatabase,
) : IBackupRepository {

    /**
     * The backup's entries with the pre-0.85.0 calendar damage undone.
     *
     * Applied before the rows are inserted, and NOT inside the transaction on
     * purpose: it is pure arithmetic over values already in memory, and holding
     * a write transaction open across it would lock the database for no reason.
     *
     * The MERGE duplicate check runs on the repaired timestamps, which is what
     * lets a re-import recognise a row it repaired the first time round — as long
     * as the two runs compute the same repair, i.e. same file boundary and same
     * device zone. Under a changed zone the instants differ and the row comes in
     * twice; the alternative, matching on the unrepaired timestamp, would fail
     * against local rows that the realignment repaired instead.
     */
    private fun repaired(
        backupEntries: List<ConsumptionEntry>,
        dayChange: BackupDayChange,
    ): List<ConsumptionEntry> = backupEntries.map { entry ->
        val fixed = LegacyDayRepair.repair(
            timestampMillis = entry.timestampMillis,
            utcOffsetSeconds = entry.utcOffsetSeconds,
            logicalDate = entry.logicalDate,
            changeHour = dayChange.hour,
            changeMinute = dayChange.minute,
        ) ?: return@map entry
        entry.copy(
            timestampMillis = fixed.timestampMillis,
            utcOffsetSeconds = fixed.utcOffsetSeconds,
        )
    }

    /**
     * REPLACE import: wipes all entries and ALL drinks (presets included), then
     * inserts the backup. The catalogue afterwards is exactly the backup's drink
     * list — a preset the backup does not contain is dropped, not kept. Backup
     * drinks carry their own `isPreset` flag, so presets present in the backup are
     * recreated verbatim. Runs in a single transaction (all-or-nothing).
     *
     * @param backupDrinks  Drinks from the backup file.
     * @param backupEntries Entries from the backup file.
     * @return [ImportStats] with the number of imported entries (skipped = 0).
     */
    override suspend fun importReplace(
        backupDrinks: List<DrinkDefinition>,
        backupEntries: List<ConsumptionEntry>,
        dayChange: BackupDayChange,
    ): ImportStats {
        var imported = 0
        val incoming = repaired(backupEntries, dayChange)
        db.withTransaction {
            entryDao.deleteAll()
            drinkDao.deleteAllDrinks()

            // Build the name → id map INSIDE the transaction, AFTER the deletes,
            // so it reflects only the rows that actually survive. After a full
            // drink wipe nothing survives, so the map starts empty and every
            // backup drink is inserted fresh below; the read is still kept
            // post-delete so the two import paths share one ordering discipline
            // and so a future partial-delete variant stays correct. A
            // getAllOnce() one-shot suspend query is transaction-safe (unlike
            // collecting the getAll() Flow).
            //
            // WHY read AFTER the delete:
            //   Capturing the map BEFORE the delete would map a backup drink onto
            //   a row that no longer exists, and the following entry insert would
            //   reference a missing parent and trip the entries→drinks FOREIGN KEY
            //   (RESTRICT), rolling the whole import back. Reading post-delete
            //   guarantees every mapped id points at a live row.
            val existingByName = drinkDao.getAllOnce().associate { it.name to it.id }

            val idMap = buildIdMap(backupDrinks, existingByName)

            incoming.forEach { entry ->
                // Use insertOrReplace (REPLACE strategy) here because backup
                // entries are re-inserted with id=0 (remapped), which means Room will
                // auto-generate a fresh primary key anyway. REPLACE is semantically
                // correct for the restore scenario and is kept here for clarity; the
                // normal insert path uses ABORT to catch unintended collisions.
                val remapped = entry.copy(id = 0, drinkId = requireMapped(idMap, entry.drinkId))
                entryDao.insertOrReplace(remapped.toEntity())
                imported++
            }
            // Rows went in without a derived day; see the file header.
            keyDao.invalidate()
        }
        return ImportStats(imported, skipped = 0)
    }

    /**
     * MERGE import: keeps existing data and adds the backup, skipping entries that
     * duplicate an existing (timestamp, drink) pair. Runs in a single transaction.
     *
     * @param backupDrinks  Drinks from the backup file.
     * @param backupEntries Entries from the backup file.
     * @return [ImportStats] with the imported and skipped counts.
     */
    override suspend fun importMerge(
        backupDrinks: List<DrinkDefinition>,
        backupEntries: List<ConsumptionEntry>,
        dayChange: BackupDayChange,
    ): ImportStats {
        var imported = 0
        var skipped = 0
        val incoming = repaired(backupEntries, dayChange)
        db.withTransaction {
            // Build the name → id map INSIDE the transaction (mirroring
            // importReplace), so this read is part of the same atomic unit as the
            // inserts below rather than a read-outside-write (TOCTOU) gap. MERGE
            // performs no deletes, so the precise timing matters less than it does
            // in REPLACE, but reading inside the transaction keeps the two import
            // paths consistent. getAllOnce() is a one-shot suspend query and is
            // therefore transaction-safe (unlike collecting the getAll() Flow).
            val existingByName = drinkDao.getAllOnce().associate { it.name to it.id }

            val idMap = buildIdMap(backupDrinks, existingByName)

            incoming.forEach { entry ->
                val remapped = entry.copy(id = 0, drinkId = requireMapped(idMap, entry.drinkId))
                if (entryDao.countByTimestampAndDrink(remapped.timestampMillis, remapped.drinkId) > 0) {
                    skipped++
                } else {
                    // Same rationale as importReplace – entries are inserted
                    // with id=0 so REPLACE is equivalent to a normal insert here.
                    entryDao.insertOrReplace(remapped.toEntity())
                    imported++
                }
            }
            // Rows went in without a derived day; see the file header.
            keyDao.invalidate()
        }
        return ImportStats(imported, skipped)
    }

    /**
     * Builds a map from backup drink ID → local database ID.
     *
     * For each backup drink:
     *   - If a drink with the same name already exists locally, reuse its ID.
     *   - Otherwise, insert the backup drink (with id=0 so Room auto-generates
     *     a new primary key) and record the returned ID.
     *
     * A freshly inserted drink's name is added to a local, growing index so that a
     * SECOND backup drink sharing the same (not-yet-existing) name reuses the id
     * just inserted for the first one, instead of inserting a duplicate row with
     * the same name. Without this, a backup containing two identically named new
     * drinks would create two local drinks with that name.
     *
     * NOTE (catalogue merge): this inserts a new-named drink even when no entry
     * references it, so `importMerge` deliberately merges the backup's drink
     * catalogue — including custom drinks that carry no entries — not only the
     * consumption entries. That is the intended contract (see [IBackupRepository]);
     * it is idempotent, because a later merge re-matches the same name. If MERGE is
     * ever redefined as entries-only, insert lazily from the entry loop instead.
     *
     * Must be called inside a `withTransaction` block.
     */
    private suspend fun buildIdMap(
        backupDrinks: List<DrinkDefinition>,
        existingByName: Map<String, Long>,
    ): Map<Long, Long> {
        val idMap = mutableMapOf<Long, Long>()
        // Mutable copy of the existing name → id snapshot, grown as new drinks are
        // inserted so later same-named backup drinks reuse the fresh id (see KDoc).
        val nameToId = existingByName.toMutableMap()
        backupDrinks.forEach { drink ->
            val localId = nameToId[drink.name]
                ?: drinkDao.insert(drink.copy(id = 0).toEntity()).also { newId ->
                    nameToId[drink.name] = newId
                }
            idMap[drink.id] = localId
        }
        return idMap
    }

    /**
     * The local drink id [backupDrinkId] was remapped to — a STRICT lookup.
     *
     * Every entry that reaches the repository through [BackupManager.parseBackupJson]
     * is guaranteed to reference a drink from the same backup (its Guard 5), and
     * [buildIdMap] maps every backup drink, so this cannot fail on the production
     * path. The former silent fallback (`idMap[…] ?: entry.drinkId`) is exactly
     * what this replaces: for a caller that bypasses the parser, a dangling raw
     * backup id either collided with a local preset id — silently attaching the
     * entry to the WRONG drink — or tripped the entries→drinks FK deep inside the
     * transaction. Failing loudly here names the actual problem instead, and the
     * surrounding `withTransaction` still rolls everything back (v0.79.0 QA fix).
     */
    private fun requireMapped(idMap: Map<Long, Long>, backupDrinkId: Long): Long = requireNotNull(idMap[backupDrinkId]) {
        "backup entry references drinkId $backupDrinkId, which is not in the backup's drinks list"
    }

    // ── Entity conversion ─────────────────────────────────────────────────────
    //
    // DrinkDefinition.toEntity() and ConsumptionEntry.toEntity() are defined
    // as `internal` extension functions in EntityMapping.kt and are therefore
    // in scope here without any further declaration. The former private copies
    // in this class have been removed as part of the C-01 DRY fix.
}
