#!/usr/bin/env bash
# vim: set et ts=4:
# =============================================================================
# Libellus Potionis - Privacy-Friendly Alcohol Tracker
# Copyright (c) 2026 Martin A. Godisch <martin@godisch.de>
# =============================================================================
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <https://www.gnu.org/licenses/>.
#
# In addition, as permitted by section 7 of the GNU General Public License,
# this program may carry additional permissions; any such permissions that
# apply to it are stated in the accompanying COPYING.md file.
#
# =============================================================================
#  release-checks/room-migrations.sh -- sourced by tools/release-check.sh (see lib.sh).
# =============================================================================


# =============================================================================
# SECTION 3 – ROOM DATABASE MIGRATIONS
#
# WHY THIS MATTERS:
#   When the Room @Database version is bumped from N-1 to N without a
#   Migration object, Room will throw an IllegalStateException on the user's
#   device because it cannot transform the existing schema.  The exported
#   schema JSON files in app/schemas/ serve as a paper trail; if the file for
#   the new version is missing the build is in an inconsistent state.
#
#   If the schema did NOT change (e.g. only logic changes, no new columns),
#   the version should NOT be bumped.  This check flags a bump without the
#   accompanying migration artefacts as a hard failure.
# =============================================================================
check_room_migrations() {
    section "3 / 15 — ROOM DATABASE MIGRATIONS"

    local db_version

    db_version=$(extract_db_version)

    if [[ -z "$db_version" ]]; then
        fail "Could not parse the Room @Database version from $APPDB_KT"
        return
    fi

    pass "Room @Database version = $db_version"

    # For version 1 there is no migration needed; start checking from v2 upwards.
    if [[ "$db_version" -ge 2 ]]; then
        local prev=$(( db_version - 1 ))
        local migration_name="MIGRATION_${prev}_${db_version}"

        # Check that the Migration object is declared
        if grep -q "val ${migration_name}" "$APPDB_KT"; then
            pass "Migration object $migration_name found in AppDatabase.kt"
        else
            fail "$migration_name not declared in AppDatabase.kt — add the migration or revert the version bump"
        fi

        # Check that the migration is registered with addMigrations()
        if grep -q "addMigrations.*${migration_name}" "$APPDB_KT"; then
            pass "$migration_name is registered with addMigrations()"
        else
            fail "$migration_name is declared but NOT passed to addMigrations() — the migration will never run"
        fi
    fi

    # Check that both the previous and current schema JSON files exist.
    # The previous file must exist to prove continuity; the current file
    # is generated by `./gradlew build` (with exportSchema = true).
    local schema_file="$SCHEMAS_DIR/${db_version}.json"
    if [[ -f "$schema_file" ]]; then
        pass "Schema file $schema_file exists"
    else
        warn "Schema file $schema_file not found — run ./gradlew build to generate it, then commit"
    fi

    if [[ "$db_version" -ge 2 ]]; then
        local prev_schema="$SCHEMAS_DIR/$(( db_version - 1 )).json"
        if [[ -f "$prev_schema" ]]; then
            pass "Previous schema file $prev_schema exists"
        else
            warn "Previous schema file $prev_schema is missing — should be committed as reference"
        fi
    fi
}
