#!/usr/bin/env python3
# vim: set et ts=4 sw=4:
# =============================================================================
# Libellus Potionis - Privacy-Friendly Alcohol Tracker
# Copyright (c) 2026 Martin A. Godisch <android@godisch.de>
# =============================================================================
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <https://www.gnu.org/licenses/>.
#
# In addition, as permitted by section 7 of the GNU General Public License,
# this program may carry additional permissions; any such permissions that
# apply to it are stated in the accompanying COPYING.md file.
# =============================================================================
"""
render-copyright.py -- build the in-app copyright document.

Concatenates the licence documents (COPYING.md + the full GPL text +
the full Apache-2.0 text) into res/raw/copyright.md, which ships inside the
APK. The Apache-2.0 text is included because Apache-2.0 section 4(a) requires
giving recipients a copy of the licence for the Apache-licensed runtime
libraries compiled into the app (see COPYING.md, "Third-Party Software").

This is the SINGLE source of truth for that concatenation: both the Makefile
rule (and its `check-guides` verification) and the Gradle
`generateCopyrightDocument` task call this script, so the two build paths can
never disagree about the generated bytes.

Format: each source file's trailing newlines are stripped, the blocks are
joined with a Markdown horizontal rule ("\\n\\n---\\n\\n") — the blank lines
around "---" make the in-app renderer treat it as a thematic break rather than
a Setext heading underline — and a single trailing newline is appended.

Usage:
    render-copyright.py OUTPUT INPUT [INPUT ...]
"""
import os
import sys

SEPARATOR = "\n\n---\n\n"


def render(inputs):
    """Return the concatenated document for the given input file paths."""
    parts = [open(p, encoding="utf-8").read().rstrip("\n") for p in inputs]
    return SEPARATOR.join(parts) + "\n"


def main(argv):
    if len(argv) < 3:
        sys.exit("usage: render-copyright.py OUTPUT INPUT [INPUT ...]")
    output, inputs = argv[1], argv[2:]
    text = render(inputs)
    parent = os.path.dirname(output)
    if parent:
        os.makedirs(parent, exist_ok=True)
    # newline="\n" pins LF line endings on every platform so the bytes match
    # the Gradle task and the check-guides comparison exactly.
    with open(output, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)


if __name__ == "__main__":
    main(sys.argv)
