#!/usr/bin/env python3
# vim: set et ts=4 sw=4:
# =============================================================================
# Libellus Potionis - Privacy-Friendly Alcohol Tracker
# Copyright (c) 2026 Martin A. Godisch <android@godisch.de>
# =============================================================================
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <https://www.gnu.org/licenses/>.
#
# =============================================================================
# render-feature-graphic.py -- deterministic Play-Store feature graphic
# =============================================================================
#
# WHAT THIS PRODUCES
#   One `featureGraphic.png` per locale, sized EXACTLY 1024x500 (the Google Play
#   feature-graphic requirement), written straight into the fastlane metadata
#   tree at:
#       fastlane/metadata/android/<locale>/images/featureGraphic.png
#
# WHY IT EXISTS
#   The previous feature graphics were generated by an image model. That made
#   their text impossible to edit cleanly and, worse, baked AI-hallucinated text
#   into the embedded "screenshots" (e.g. a garbled PDF report). This script
#   composes the graphic DETERMINISTICALLY from three inputs the project already
#   controls, so it is reproducible and trivially re-localizable:
#       1. per-locale marketing copy  -> fastlane/.../<locale>/feature-graphic.txt
#       2. the REAL, current screenshots produced by `make screenshots`
#          (01_today.png as the phone, 07_report_page_1.png as the report page)
#       3. the app's own launcher icon (foreground PNG + adaptive background)
#
# WHY SVG + rsvg-convert (and not Pillow)
#   The layout is markup (gradients, rounded rects, a rotated "paper", clipped
#   screenshots), which is far more legible and tweakable as SVG than as Pillow
#   pixel math. The one determinism caveat of librsvg -- that text rendering
#   depends on whatever fonts the host happens to have -- is removed by pinning a
#   bundled font: we point fontconfig at tools/fonts/ ONLY (see
#   _render_png), so the same Inter files are always used regardless of host.
#
# RUNTIME DEPENDENCIES (kept deliberately small)
#   * python3 standard library only (no third-party Python packages),
#   * rsvg-convert (Debian package `librsvg2-bin`),
#   * the bundled fonts under tools/fonts/Inter/.
#   The static Inter instances were prepared once with fontTools; this script
#   never needs fontTools itself.
#
# TEXT WRAPPING
#   Marketing copy is wrapped here so the per-locale .txt files stay free of
#   layout concerns -- editors change words, not line breaks. Wrapping uses an
#   approximate advance-width model (see _text_width); it is intentionally
#   slightly conservative so a line never overflows its column. An explicit
#   line break can still be forced by writing a literal '\n' inside a value.
# =============================================================================

import argparse
import base64
import html
import io
import os
import re
import shutil
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path

from PIL import Image, ImageDraw

# ── Paths ────────────────────────────────────────────────────────────────────
# The script now lives in tools/ at the repository root (a sibling of android/).
TOOLS_DIR = Path(__file__).resolve().parent
REPO_ROOT = TOOLS_DIR.parent
ANDROID_DIR = REPO_ROOT / "android"
FONT_DIR = TOOLS_DIR / "fonts"
META_DIR = REPO_ROOT / "fastlane" / "metadata" / "android"
ICON_FG = (
    ANDROID_DIR
    / "app/src/main/res/drawable-xxxhdpi/ic_launcher_foreground.png"
)
# The adaptive-icon background colour (res/values/colors.xml: ic_launcher_background).
ICON_BG = "#1A1E2B"

# The GPLv3 "Free as in Freedom" license badge (red variant), inlined as a small
# corner badge. Source/licence are credited in COPYING.md.
GPL_LOGO = REPO_ROOT / "fastlane" / "gpl-v3-logo.svg"

# The per-locale "Get it on F-Droid" badge (fdroid/get-it-on-<lang>.svg), placed
# to the right of the GPL logo. Its lettering is LIVE <text> -- "GET IT ON" in
# DejaVu Sans and "F-Droid" in Rokkitt Bold -- so those two families must be
# resolvable by the pinned fontconfig; they are bundled under tools/fonts/
# alongside Inter (see COPYING.md and `make rokkitt-bold`).
BADGE_DIR = REPO_ROOT / "fdroid"

# ── Canvas (Google Play feature-graphic spec) ────────────────────────────────
W, H = 1024, 500
# The store PNG must be exactly W x H. A high-resolution companion
# (featureGraphic-4K.png) is additionally rendered at HQ_SCALE x that size for
# press/web/print use; it is NOT uploaded to Play (see render_locale).
HQ_SCALE = 4  # 4 x (1024 x 500) = 4096 x 2000

# ── Palette ──────────────────────────────────────────────────────────────────
BG_TOP = "#11192a"      # background gradient, top-left
BG_BOTTOM = "#0a0f18"   # background gradient, bottom-right
GLOW = "#e0a93c"        # warm amber glow behind the phone
TEXT_PRIMARY = "#ffffff"
TEXT_SECONDARY = "#c3ccd8"
ACCENT = "#e0a93c"      # bullet icons / highlights
BULLET_BG = "rgba(255,255,255,0.055)"
BULLET_STROKE = "rgba(255,255,255,0.10)"
PHONE_BEZEL = "#05080d"
PHONE_STROKE = "#27313f"

# ── Approximate per-character advance widths (fraction of font size) ─────────
# Inter is proportional, so a flat factor wraps poorly. This coarse class model
# is accurate enough to wrap a handful of marketing lines without overflow; it
# is deliberately a hair wide so wrapping errs toward breaking early. Values are
# fractions of the font size in user units (px).
#
# CJK note: Han, kana, Hangul and fullwidth punctuation are (near) EM-square, so
# they advance ~1.0 em -- roughly double the Latin average. Treating them with
# the Latin classes below would under-measure a CJK line by ~2x and never wrap
# it (there are no spaces to break at either), so it would shoot off the canvas.
# _is_cjk flags these code points; _char_width gives them a full-em advance and
# _wrap treats each as its own break opportunity.
def _is_cjk(ch: str) -> bool:
    """True for CJK ideographs, kana, Hangul and CJK/fullwidth punctuation.

    These are the scripts that (a) render at ~1 em width and (b) allow a line
    break between (almost) any two adjacent characters, unlike space-delimited
    Latin. The ranges intentionally include the CJK punctuation block (、。，：)
    and the Fullwidth Forms block (！：％) so those wrap and measure like the Han
    text they sit in.
    """
    o = ord(ch)
    return (
        0x1100 <= o <= 0x11FF or    # Hangul Jamo
        0x2E80 <= o <= 0x2EFF or    # CJK Radicals Supplement
        0x3000 <= o <= 0x303F or    # CJK Symbols and Punctuation
        0x3040 <= o <= 0x30FF or    # Hiragana + Katakana
        0x3130 <= o <= 0x318F or    # Hangul Compatibility Jamo
        0x3400 <= o <= 0x4DBF or    # CJK Unified Ideographs Extension A
        0x4E00 <= o <= 0x9FFF or    # CJK Unified Ideographs
        0xA960 <= o <= 0xA97F or    # Hangul Jamo Extended-A
        0xAC00 <= o <= 0xD7A3 or    # Hangul Syllables
        0xF900 <= o <= 0xFAFF or    # CJK Compatibility Ideographs
        0xFF00 <= o <= 0xFF60 or    # Fullwidth Forms (！：％ …)
        0xFFE0 <= o <= 0xFFE6       # Fullwidth signs (￥ …)
    )


_NARROW = set("iIl1.,;:'!|()[]{}/\\ ")
_WIDE = set("mMwW@")
def _char_width(ch: str, size: float) -> float:
    if _is_cjk(ch):
        return size * 1.0       # ~EM-square advance (Han, kana, Hangul, fullwidth)
    if ch == " ":
        return size * 0.27
    if ch in _NARROW:
        return size * 0.33
    if ch in _WIDE:
        return size * 0.82
    if ch in "%&":
        return size * 0.70
    if ch.isupper():
        return size * 0.61
    return size * 0.53


def _text_width(text: str, size: float) -> float:
    """Approximate the rendered width of `text` at `size` px (see _char_width)."""
    return sum(_char_width(c, size) for c in text)


def _wrap(text: str, size: float, max_width: float) -> list[str]:
    """Greedy wrap honouring explicit '\\n' breaks, Latin words AND CJK runs.

    Break opportunities are: at every space (which then renders as a single
    space when both sides share a line) and between CJK characters (which carry
    no spaces). Latin words -- maximal runs of non-space, non-CJK characters --
    stay intact. This keeps the previous behaviour verbatim for space-delimited
    Latin copy while letting CJK taglines wrap at all (they otherwise form one
    unbreakable, oversized line).
    """
    lines: list[str] = []
    for hard_line in text.split("\\n"):
        # Tokenise into units, remembering whether a space preceded each one.
        units: list[tuple[str, bool]] = []
        i, n, pending_space = 0, len(hard_line), False
        while i < n:
            c = hard_line[i]
            if c == " ":
                pending_space = True
                i += 1
            elif _is_cjk(c):
                units.append((c, pending_space))
                pending_space = False
                i += 1
            else:
                j = i
                while j < n and hard_line[j] != " " and not _is_cjk(hard_line[j]):
                    j += 1
                units.append((hard_line[i:j], pending_space))
                pending_space = False
                i = j
        if not units:
            lines.append("")
            continue
        cur = units[0][0]                      # leading space (if any) dropped
        for tok, space_before in units[1:]:
            sep = " " if space_before else ""
            if _text_width(cur + sep + tok, size) <= max_width:
                cur += sep + tok
            else:
                lines.append(cur)
                cur = tok
        lines.append(cur)
    return lines


# ── SVG helpers ──────────────────────────────────────────────────────────────
def _esc(text: str) -> str:
    """Escape text for inclusion in an SVG text node."""
    return html.escape(text, quote=True)


def _data_uri(path: Path) -> str:
    """Read a PNG and return a base64 data: URI so the SVG is self-contained."""
    raw = path.read_bytes()
    return "data:image/png;base64," + base64.b64encode(raw).decode("ascii")


def _tspans(lines: list[str], x: float, y: float, line_height: float) -> str:
    """Render wrapped lines as <tspan>s sharing one <text> anchor."""
    out = []
    for i, line in enumerate(lines):
        dy = 0 if i == 0 else line_height
        out.append(
            f'<tspan x="{x:.1f}" dy="{dy:.1f}">{_esc(line)}</tspan>'
        )
    return "".join(out)


def _svg_box_and_inner(path: Path) -> tuple[float, float, str]:
    """Parse an SVG file into its coordinate box and inner markup.

    Returns ``(box_width, box_height, inner)`` where the box comes from the root
    ``viewBox`` if present, else from the root ``width``/``height`` (the F-Droid
    badge exports carry only width/height, no viewBox -- both paths are handled).
    ``inner`` is everything between the root ``<svg …>`` tag and its closing
    ``</svg>``. Callers re-wrap ``inner`` in a nested ``<svg>`` with their own
    placement box, so the artwork keeps its aspect ratio and is drawn in the SAME
    rsvg pass as the rest of the graphic (no extra rasterisation). Replacing an
    asset with a differently sized export therefore needs no code change.
    """
    raw = path.read_text(encoding="utf-8")
    root = re.search(r"<svg\b[^>]*>", raw)
    if root is None:
        raise ValueError(f"{path}: no <svg> root element")
    root_tag = root.group(0)
    vb = re.search(r'viewBox="\s*([\d.\s-]+)"', root_tag)
    if vb:
        nums = vb.group(1).split()
        vb_w, vb_h = float(nums[2]), float(nums[3])
    else:
        vb_w = float(re.search(r'\bwidth="([\d.]+)', root_tag).group(1))
        vb_h = float(re.search(r'\bheight="([\d.]+)', root_tag).group(1))
    inner = raw[root.end():raw.rindex("</svg>")]
    return vb_w, vb_h, inner


def _svg_ink_bbox(path: Path) -> tuple[float, float, float, float]:
    """Return the VISIBLE ink bounding box (min_x, min_y, width, height) of an SVG.

    The F-Droid badge exports sit on a 646x250 canvas with a wide TRANSPARENT
    margin (~43 px per side); scaling by the canvas would therefore render the
    visible badge much shorter than a logo scaled the same way. Cropping the
    nested <svg>'s viewBox to this ink box lets the badge be matched to the GPL
    logo by VISIBLE height instead of by canvas height.

    The box is computed from the BACKGROUND shapes (<rect>/<circle>/<ellipse>)
    with their nested transforms applied. That is exactly right for the badge: the
    rounded-rectangle background bounds the whole button, and the wordmark (<text>)
    and robot (<path>) sit inside it -- so paths and text are deliberately ignored,
    which keeps this free of a fragile path-data parser. Only affine
    translate/scale/matrix transforms occur in these assets, so no rotation
    handling is needed. If an asset carries no such background shape, the function
    falls back to the full canvas box.
    """

    def mul(m, n):
        a, b, c, d, e, f = m
        A, B, C, D, E, F = n
        return (a * A + c * B, b * A + d * B, a * C + c * D, b * C + d * D,
                a * E + c * F + e, b * E + d * F + f)

    def parse(s):
        m = (1.0, 0.0, 0.0, 1.0, 0.0, 0.0)
        for name, args in re.findall(r"(\w+)\s*\(([^)]*)\)", s or ""):
            v = [float(t) for t in re.split(r"[\s,]+", args.strip()) if t]
            if name == "translate":
                m = mul(m, (1, 0, 0, 1, v[0], v[1] if len(v) > 1 else 0))
            elif name == "scale":
                m = mul(m, (v[0], 0, 0, v[1] if len(v) > 1 else v[0], 0, 0))
            elif name == "matrix":
                m = mul(m, tuple(v))
        return m

    box = [float("inf"), float("inf"), float("-inf"), float("-inf")]

    def add(m, x, y):
        a, b, c, d, e, f = m
        px, py = a * x + c * y + e, b * x + d * y + f
        box[0] = min(box[0], px); box[1] = min(box[1], py)
        box[2] = max(box[2], px); box[3] = max(box[3], py)

    def walk(el, m):
        t = el.get("transform")
        cur = mul(m, parse(t)) if t else m
        tag = el.tag.split("}")[-1]
        if tag == "rect":
            x = float(el.get("x", 0)); y = float(el.get("y", 0))
            w = float(el.get("width", 0)); h = float(el.get("height", 0))
            add(cur, x, y); add(cur, x + w, y + h)
        elif tag in ("circle", "ellipse"):
            cx = float(el.get("cx", 0)); cy = float(el.get("cy", 0))
            rx = float(el.get("r", el.get("rx", 0)))
            ry = float(el.get("r", el.get("ry", 0)))
            add(cur, cx - rx, cy - ry); add(cur, cx + rx, cy + ry)
        for child in el:
            walk(child, cur)

    walk(ET.parse(path).getroot(), (1.0, 0.0, 0.0, 1.0, 0.0, 0.0))
    if box[0] == float("inf"):          # no background shape found -> full canvas
        vb_w, vb_h, _ = _svg_box_and_inner(path)
        return 0.0, 0.0, vb_w, vb_h
    return box[0], box[1], box[2] - box[0], box[3] - box[1]


def _logo_nested(x: float, y: float, width: float, color: str = "#ffffff") -> str:
    """Inline the GPLv3 logo (fastlane/gpl-v3-logo.svg) as a nested <svg>.

    The bundled file is the 'Free as in Freedom' GPLv3 badge on a transparent
    background -- exactly one logo. Its artwork is a single solid colour
    (#bd0000); we recolour it to `color` at embed time (white reads best on the
    dark canvas) by substituting that fill, leaving the stored source untouched.
    Scales to `width` keeping aspect ratio (see _svg_box_and_inner).
    """
    vb_w, vb_h, inner = _svg_box_and_inner(GPL_LOGO)
    inner = re.sub(r"#bd0000", color, inner, flags=re.IGNORECASE)
    height = width * vb_h / vb_w
    return (
        f'<svg x="{x:.1f}" y="{y:.1f}" width="{width:.1f}" height="{height:.1f}" '
        f'viewBox="0 0 {vb_w:g} {vb_h:g}">{inner}</svg>'
    )


def _badge_nested(path: Path, x: float, y: float, height: float) -> str:
    """Inline a 'Get it on F-Droid' badge as a nested <svg>, scaled to `height`.

    Unlike the GPL logo the badge is embedded with its ORIGINAL colours -- F-Droid
    brand artwork must not be recoloured -- so `inner` is emitted verbatim.

    `height` is the target VISIBLE height (so the badge matches the GPL logo, which
    fills its own canvas). The badge canvas, by contrast, carries a wide
    transparent margin, so we crop the nested viewBox to the badge's INK box
    (_svg_ink_bbox) and scale THAT to `height`; the width then follows from the
    ink aspect ratio. Cropping via the viewBox costs nothing -- the same rsvg pass
    just maps the ink box, not the padded canvas, into the placement rectangle.

    The badge's live <text> ("GET IT ON" in DejaVu Sans, "F-Droid" in Rokkitt
    Bold) resolves against the pinned bundled fonts under tools/fonts/. Its
    internal `xlink:href`/`id` references (a gradient `<defs>` entry) stay valid
    because the outer document declares the xlink namespace and each graphic
    embeds exactly one badge, so those ids cannot collide.
    """
    _, _, inner = _svg_box_and_inner(path)
    vx, vy, vw, vh = _svg_ink_bbox(path)
    width = height * vw / vh
    return (
        f'<svg x="{x:.1f}" y="{y:.1f}" width="{width:.1f}" height="{height:.1f}" '
        f'viewBox="{vx:g} {vy:g} {vw:g} {vh:g}">{inner}</svg>'
    )


def _badge_for_locale(locale: str) -> Path:
    """Return the 'Get it on F-Droid' badge SVG matching `locale`'s language.

    The badge files are named ``fdroid/get-it-on-<tag>.svg``, where ``<tag>`` is
    the language subtag in lower case, keeping (and lower-casing) any region:
    ``pt-BR`` -> ``pt-br``, ``zh-CN`` -> ``zh-cn``. To pick one, we try the most
    specific name first and fall back to progressively broader ones, ending at
    the English badge -- so a locale that ships no badge of its own (e.g.
    ``no-NO``, ``uk``) still renders a valid, if English, badge instead of
    raising::

        de-DE -> get-it-on-de-de.svg?  (no)  -> get-it-on-de.svg   (yes)
        en-US -> get-it-on-en-us.svg?  (no)  -> get-it-on-en.svg   (yes)
        pt-BR -> get-it-on-pt-br.svg   (yes)
        cs-CZ -> get-it-on-cs-cz.svg?  (no)  -> get-it-on-cs.svg   (yes)
        zh-CN -> get-it-on-zh-cn.svg   (yes)
        no-NO -> get-it-on-no-no.svg? get-it-on-no.svg?  (no) -> get-it-on-en.svg

    This language-first fallback is what lets the store-locale directories use
    Google Play's region-qualified codes (``cs-CZ``, ``ja-JP``, … — see the
    v0.79.0 store-locale migration) while the badge artwork keeps its upstream
    bare-language file names: every renamed locale still resolves to the same
    badge as before.
    """
    tag = locale.lower()
    candidates = [tag]                          # full tag, e.g. "pt-br", "de-de"
    if "-" in tag:
        candidates.append(tag.split("-", 1)[0])  # bare language, e.g. "de", "pt"
    candidates.append("en")                     # ultimate fallback (always present)
    for cand in candidates:
        path = BADGE_DIR / f"get-it-on-{cand}.svg"
        if path.is_file():
            return path
    # Unreachable in practice: the English badge is always bundled. Returning it
    # explicitly keeps the function total (it never returns None).
    return BADGE_DIR / "get-it-on-en.svg"


# The Noto Sans CJK families (bundled under tools/fonts/NotoSansCJK/) used as the
# fallback after Inter for the CJK locales. Inter has no CJK/Hangul glyphs, so
# without this the CJK copy would render as missing-glyph boxes. Region-specific
# families are chosen so each locale gets its expected Han variants (SC vs TC)
# and JP/KR kana/Hangul shaping. Locales without a CJK family (all the
# Latin/Greek/Cyrillic ones) get no CJK fallback and render from Inter exactly
# as before.
#
# Keyed by LANGUAGE SUBTAG (and, for Chinese, the region), NOT by the literal
# fastlane directory name: the directory names are Google Play's store-locale
# codes and may be region-qualified ("ja-JP", "ko-KR" — see the v0.79.0
# store-locale migration in CHANGELOG.md), while the font choice depends only on
# the language/script. A dict keyed by the old bare "ja"/"ko" names silently
# stopped matching after the rename — exactly the trap this parser avoids.
_CJK_BY_LANGUAGE = {
    "ja": "Noto Sans CJK JP",
    "ko": "Noto Sans CJK KR",
}


def _cjk_family_for_locale(locale: str) -> str | None:
    """Return the Noto Sans CJK family to append after Inter, or None.

    ``locale`` is the fastlane store-locale directory name (e.g. ``ja-JP``,
    ``zh-CN``, ``de-DE``). The language subtag selects the family; for Chinese
    the region decides between the Simplified (CN/SG) and Traditional (TW/HK/MO)
    Han variants, defaulting to Simplified for a bare ``zh``.
    """
    parts = locale.split("-")
    language = parts[0].lower()
    region = parts[-1].upper() if len(parts) > 1 else ""
    if language == "zh":
        traditional = region in {"TW", "HK", "MO"}
        return "Noto Sans CJK TC" if traditional else "Noto Sans CJK SC"
    return _CJK_BY_LANGUAGE.get(language)


def _font_family(cjk_family: str | None) -> str:
    """Build the SVG font-family value: Inter first, then the CJK family if any.

    fontconfig/pango fall back per glyph, so Latin/digits/punctuation keep coming
    from Inter (weights 400/600/700) while Han/kana/Hangul resolve to the CJK
    family. The value is emitted into a double-quoted SVG attribute, so the CJK
    family name is wrapped in single quotes.
    """
    return "Inter" if not cjk_family else f"Inter, '{cjk_family}'"


# ── Locale copy ──────────────────────────────────────────────────────────────
class Copy:
    """Parsed marketing copy for one locale (see feature-graphic.txt format)."""

    def __init__(self, title: str, taglines: list[str], bullets: list[str]):
        self.title = title
        self.taglines = taglines      # one entry per paragraph
        self.bullets = bullets        # exactly four short phrases

    @staticmethod
    def load(path: Path) -> "Copy":
        title = ""
        taglines: list[str] = []
        bullets: list[str] = []
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.rstrip("\n")
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if ":" not in line:
                raise ValueError(f"{path}: line without 'key:' prefix: {line!r}")
            key, _, value = line.partition(":")
            key = key.strip()
            value = value.strip()
            if key == "title":
                title = value
            elif key == "tagline":
                taglines.append(value)
            elif key == "bullet":
                bullets.append(value)
            else:
                raise ValueError(f"{path}: unknown key {key!r}")
        if not title:
            raise ValueError(f"{path}: missing 'title:'")
        if len(bullets) != 4:
            raise ValueError(f"{path}: expected exactly 4 'bullet:' lines, got {len(bullets)}")
        return Copy(title, taglines, bullets)


# ── Bullet icons (simple line glyphs, drawn at a 0..24 unit scale) ───────────
# Each value is the inner markup of a <g> already translated/scaled into place;
# they use currentColor so the caller sets the stroke/fill colour once.
# A bar chart with a DOWNWARD trend line + arrow over it: the goal of setting and
# keeping limits is to bring consumption DOWN, so the bars sit below and the arrow
# points down. Mirrors the reference graphic, which paired bars with the arrow.
_ICON_TREND = (
    '<g fill="currentColor" fill-opacity="0.5">'
    '<rect x="2" y="11.2" width="3.6" height="10.8" rx="0.6"/>'
    '<rect x="7" y="16.6" width="3.6" height="5.4" rx="0.6"/>'
    '<rect x="12" y="13.9" width="3.6" height="8.1" rx="0.6"/>'
    '<rect x="17" y="19.3" width="3.6" height="2.7" rx="0.6"/>'
    '</g>'
    '<polyline points="2,4 8,8 13,5 21,11" fill="none" stroke="currentColor" '
    'stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"/>'
    '<polyline points="15,11 21,11 21,5" fill="none" stroke="currentColor" '
    'stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"/>'
)
_ICON_SHIELD = (
    '<path d="M12 2 L20 5 V11 C20 16 16.5 20 12 22 C7.5 20 4 16 4 11 V5 Z" '
    'fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/>'
    '<path d="M8.5 12 L11 14.5 L15.5 9.5" fill="none" stroke="currentColor" '
    'stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>'
)
_ICON_DOC = (
    '<path d="M6 2 H14 L19 7 V22 H6 Z" fill="none" stroke="currentColor" '
    'stroke-width="2" stroke-linejoin="round"/>'
    '<path d="M14 2 V7 H19" fill="none" stroke="currentColor" '
    'stroke-width="2" stroke-linejoin="round"/>'
    '<line x1="9" y1="12" x2="16" y2="12" stroke="currentColor" '
    'stroke-width="2" stroke-linecap="round"/>'
    '<line x1="9" y1="16" x2="16" y2="16" stroke="currentColor" '
    'stroke-width="2" stroke-linecap="round"/>'
)
_ICON_STAR = (
    '<path d="M12 2.5 L14.9 8.6 L21.5 9.5 L16.7 14.1 L17.9 20.7 '
    'L12 17.5 L6.1 20.7 L7.3 14.1 L2.5 9.5 L9.1 8.6 Z" '
    'fill="currentColor" stroke="currentColor" stroke-width="1" '
    'stroke-linejoin="round"/>'
)
_BULLET_ICONS = [_ICON_TREND, _ICON_SHIELD, _ICON_DOC, _ICON_STAR]


# ── Pillow: build the phone upright and perspective-warp it to lean back ─────
def _solve8(rows: list[list[float]], rhs: list[float]) -> list[float]:
    """Solve an 8x8 linear system by Gaussian elimination with partial pivoting.

    Used only to derive the perspective-warp coefficients. Pure Python keeps the
    tool free of a numpy dependency and the result deterministic.
    """
    n = len(rhs)
    a = [rows[i][:] + [rhs[i]] for i in range(n)]
    for col in range(n):
        piv = max(range(col, n), key=lambda r: abs(a[r][col]))
        a[col], a[piv] = a[piv], a[col]
        pivot = a[col][col]
        for j in range(col, n + 1):
            a[col][j] /= pivot
        for r in range(n):
            if r != col and a[r][col]:
                factor = a[r][col]
                for j in range(col, n + 1):
                    a[r][j] -= factor * a[col][j]
    return [a[i][n] for i in range(n)]


def _perspective_coeffs(dst, src):
    """The 8 PIL PERSPECTIVE coefficients that map each OUTPUT point in `dst` to
    the INPUT point in `src`, so the source rectangle is displayed inside the dst
    quadrilateral."""
    m: list[list[float]] = []
    b: list[float] = []
    for (X, Y), (x, y) in zip(dst, src):
        m.append([X, Y, 1, 0, 0, 0, -x * X, -x * Y]); b.append(x)
        m.append([0, 0, 0, X, Y, 1, -y * X, -y * Y]); b.append(y)
    return _solve8(m, b)


def _render_phone_png(today_png: Path, w: int, h: int, r: int, bezel: int) -> bytes:
    """Build the phone (rounded bezel + screenshot + island) UPRIGHT, then
    perspective-warp it so it turns slightly about its VERTICAL axis -- the LEFT
    edge recedes (farther, shorter) and the RIGHT edge stays near -- and return the
    RGBA PNG bytes.

    SVG transforms are affine and cannot express perspective, so this single step
    is done in Pillow; the warped phone is then embedded as one image in the SVG.
    It is rendered at SS x the on-canvas size for crisp downscaling and is
    deterministic for a given Pillow version and inputs.
    """
    ss = 3
    wp, hp = w * ss, h * ss
    rad, bz, scr_r = r * ss, bezel * ss, (r - bezel) * ss

    phone = Image.new("RGBA", (wp, hp), (0, 0, 0, 0))
    ImageDraw.Draw(phone).rounded_rectangle(
        [0, 0, wp - 1, hp - 1], radius=rad,
        fill=(5, 8, 13, 255), outline=(39, 49, 63, 255), width=max(1, ss),
    )

    # Screen: cover-scale the screenshot to the inner area, centred horizontally
    # and top-aligned (matching the previous xMidYMin "slice"), clipped to a
    # rounded rect.
    sw, sh = wp - 2 * bz, hp - 2 * bz
    shot = Image.open(today_png).convert("RGBA")
    scale = max(sw / shot.width, sh / shot.height)
    shot = shot.resize(
        (max(1, round(shot.width * scale)), max(1, round(shot.height * scale))),
        Image.LANCZOS,
    )
    left = (shot.width - sw) // 2
    shot = shot.crop((left, 0, left + sw, sh))
    mask = Image.new("L", (sw, sh), 0)
    ImageDraw.Draw(mask).rounded_rectangle([0, 0, sw - 1, sh - 1], radius=scr_r, fill=255)
    phone.paste(shot, (bz, bz), mask)

    # Dynamic-island pill near the top of the screen.
    iw, ih = 44 * ss, 12 * ss
    ix, iy = (wp - iw) // 2, 14 * ss
    ImageDraw.Draw(phone).rounded_rectangle(
        [ix, iy, ix + iw, iy + ih], radius=ih // 2, fill=(5, 8, 13, 255),
    )

    # Lean back about the VERTICAL axis: the LEFT edge recedes (moves inward and
    # is shortened top+bottom), while the RIGHT edge stays full and near. dst is
    # the output trapezoid, src the upright rect (corners TL, TR, BR, BL).
    lx, ly = round(wp * 0.06), round(hp * 0.03)
    dst = [(lx, ly), (wp, 0), (wp, hp), (lx, hp - ly)]
    src = [(0, 0), (wp, 0), (wp, hp), (0, hp)]
    coeffs = _perspective_coeffs(dst, src)
    warped = phone.transform(
        (wp, hp), Image.PERSPECTIVE, coeffs,
        resample=Image.BICUBIC, fillcolor=(0, 0, 0, 0),
    )

    buf = io.BytesIO()
    warped.save(buf, format="PNG", optimize=True)
    return buf.getvalue()


def _build_svg(copy: Copy, today_png: Path, report_png: Path, badge_svg: Path,
               cjk_family: str | None = None) -> str:
    """Assemble the full SVG document string for one locale.

    `cjk_family` (see _cjk_family_for_locale) is appended after Inter in the
    text font-family for CJK locales; None keeps the Latin-only Inter family.
    """
    font_family = _font_family(cjk_family)
    report_uri = _data_uri(report_png)
    icon_uri = _data_uri(ICON_FG)

    parts: list[str] = []
    parts.append(
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'xmlns:xlink="http://www.w3.org/1999/xlink" '
        f'width="{W}" height="{H}" viewBox="0 0 {W} {H}">'
    )

    # ── Defs: gradients, clips, shadow filter ────────────────────────────────
    parts.append("<defs>")
    parts.append(
        f'<linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">'
        f'<stop offset="0" stop-color="{BG_TOP}"/>'
        f'<stop offset="1" stop-color="{BG_BOTTOM}"/>'
        f'</linearGradient>'
    )
    parts.append(
        f'<radialGradient id="glow" cx="0.5" cy="0.5" r="0.5">'
        f'<stop offset="0" stop-color="{GLOW}" stop-opacity="0.42"/>'
        f'<stop offset="0.55" stop-color="{GLOW}" stop-opacity="0.12"/>'
        f'<stop offset="1" stop-color="{GLOW}" stop-opacity="0"/>'
        f'</radialGradient>'
    )
    # Gradient for the phone's right-side depth edge: lighter where it meets the
    # front face (a metal highlight), darkening toward the back.
    parts.append(
        '<linearGradient id="edge" x1="0" y1="0" x2="1" y2="0">'
        '<stop offset="0" stop-color="#3a4759"/>'
        '<stop offset="0.5" stop-color="#10151e"/>'
        '<stop offset="1" stop-color="#05080d"/>'
        '</linearGradient>'
    )
    # Phone geometry. The phone is built and perspective-warped with Pillow (see
    # _render_phone_png) and embedded as a single image, so there is no SVG screen
    # clip here. ph_r/bezel drive the warp; ph_x/ph_y place the result; bullets are
    # centred on ph_y + ph_h/2.
    ph_x, ph_y, ph_w, ph_h, ph_r = 598, 52, 196, 396, 18
    bezel = 6  # bezel thickness (inset from body edge to screen)
    parts.append(
        '<filter id="shadow" x="-30%" y="-30%" width="160%" height="160%">'
        '<feDropShadow dx="0" dy="6" stdDeviation="10" '
        'flood-color="#000000" flood-opacity="0.45"/></filter>'
    )
    # Icon tile clip.
    parts.append(
        '<clipPath id="iconclip"><rect x="48" y="54" width="86" height="86" '
        'rx="20" ry="20"/></clipPath>'
    )
    parts.append("</defs>")

    # ── Background + glow ────────────────────────────────────────────────────
    parts.append(f'<rect width="{W}" height="{H}" fill="url(#bg)"/>')
    parts.append(
        '<ellipse cx="696" cy="250" rx="350" ry="300" fill="url(#glow)"/>'
    )

    # NOTE: the report "paper" and the phone are drawn LAST (see end of this
    # function), so the phone overlaps the right edge of the feature boxes.

    # ── Left column: icon tile + title + taglines ────────────────────────────
    parts.append(
        f'<rect x="48" y="54" width="86" height="86" rx="20" ry="20" '
        f'fill="{ICON_BG}"/>'
    )
    parts.append(
        f'<image x="48" y="54" width="86" height="86" clip-path="url(#iconclip)" '
        f'xlink:href="{icon_uri}"/>'
    )
    # White frame so the (dark) icon tile separates from the dark background,
    # mirroring the reference graphic. Drawn LAST so it sits above the icon.
    parts.append(
        '<rect x="48" y="54" width="86" height="86" rx="20" ry="20" fill="none" '
        'stroke="#ffffff" stroke-opacity="0.9" stroke-width="2.5"/>'
    )

    title_y = 196
    parts.append(
        f'<text x="48" y="{title_y}" font-family="{font_family}" font-weight="700" '
        f'font-size="30" letter-spacing="0.4" fill="{TEXT_PRIMARY}">'
        f'{_esc(copy.title)}</text>'
    )

    # Taglines: each paragraph wrapped to the left column width.
    tag_size = 21
    tag_lh = 28
    y = title_y + 46
    for para in copy.taglines:
        lines = _wrap(para, tag_size, max_width=320)
        parts.append(
            f'<text x="48" y="{y:.1f}" font-family="{font_family}" font-weight="400" '
            f'font-size="{tag_size}" fill="{TEXT_SECONDARY}">'
            f'{_tspans(lines, 48, y, tag_lh)}</text>'
        )
        y += tag_lh * len(lines) + 18  # paragraph gap

    # Bottom corners: the "Get it on F-Droid" badge (original colours) in the
    # bottom-LEFT and the GPLv3 "Free as in Freedom" logo (recoloured WHITE) in
    # the bottom-RIGHT, each inset by EQUAL bottom + side margins (48 px) so the
    # two corners mirror one another. Both share the same bottom baseline and the
    # same VISIBLE height.
    #
    # logo_w drives that shared height (the badge is matched to the logo's visible
    # height). It is kept at 96 -- the reduced size introduced earlier -- so the
    # pair renders a little smaller than the logo's native 112. NOTE: the original
    # phone-clearance reason for the reduction no longer strictly applies now that
    # the WIDE badge sits bottom-LEFT (clear of the phone) and the NARROW logo sits
    # bottom-RIGHT (its left edge x≈880 clears the phone body + soft shadow ≈823 by
    # ~57 px); the reduced size is retained by choice and may be raised to 112.
    margin = 48.0
    logo_w = 96.0
    logo_h = logo_w * 358.0 / 720.0
    baseline_y = H - margin - logo_h
    # F-Droid badge, bottom-LEFT (x = margin): original brand colours, cropped to
    # its ink box and scaled to the shared visible height (see _badge_nested). The
    # bottom-left corner is clear of the phone and the PDF "paper", so it is drawn
    # here in normal order.
    parts.append(_badge_nested(badge_svg, margin, baseline_y, logo_h))

    # The GPLv3 logo mirrors this into the bottom-RIGHT corner, but it is appended
    # LATER -- after the report "paper" -- so it sits IN FRONT of the tilted PDF
    # screenshot instead of behind it. See the report/phone block below.
    # ── Centre column: four feature bullets ──────────────────────────────────
    # The boxes are wide enough that their RIGHT edge (bx+bw) tucks behind the
    # phone (drawn afterwards), as in the reference; the label column is capped
    # (lab_max) so wrapped text never runs under the phone. Every box shares ONE
    # height, sized to fit the TALLEST label (most lines) with EQUAL padding above
    # and below the text block; the whole stack is then centred on the phone, which
    # leaves a little more breathing room above and below it.
    bx, bw = 372, 268
    bgap = 13
    lab_size = 18
    lab_lh = 22
    lab_max = 150
    cap_h = 0.72 * lab_size      # approx. cap height (baseline -> cap top)
    descent = 0.21 * lab_size    # approx. descender depth
    pad = 9                      # equal padding above and below the text block
    wrapped = [_wrap(t, lab_size, max_width=lab_max) for t in copy.bullets]
    max_lines = max(len(w) for w in wrapped)
    text_h = cap_h + (max_lines - 1) * lab_lh + descent
    bh = text_h + 2 * pad
    stack_h = 4 * bh + 3 * bgap
    by = (ph_y + ph_h / 2) - stack_h / 2
    for icon, lines in zip(_BULLET_ICONS, wrapped):
        box_cy = by + bh / 2
        parts.append(
            f'<rect x="{bx}" y="{by:.1f}" width="{bw}" height="{bh:.1f}" rx="16" '
            f'ry="16" fill="{BULLET_BG}" stroke="{BULLET_STROKE}" stroke-width="1"/>'
        )
        # Icon: 24-unit glyph scaled to ~30px, centred on the box centre line.
        parts.append(
            f'<g transform="translate({bx + 18:.1f} {box_cy - 15:.1f}) '
            f'scale({30 / 24:.4f})" color="{ACCENT}">{icon}</g>'
        )
        # Label: its VISUAL centre is aligned to the box centre, so a single-line
        # label sits level with the icon, and a multi-line label keeps EQUAL padding
        # above and below (using cap-height/descent rather than full line slots,
        # which is what previously pushed the text up and left a gap underneath).
        first_baseline = box_cy - (len(lines) - 1) * lab_lh / 2 + (cap_h - descent) / 2
        parts.append(
            f'<text x="{bx + 60}" y="{first_baseline:.1f}" font-family="{font_family}" '
            f'font-weight="600" font-size="{lab_size}" fill="{TEXT_PRIMARY}">'
            f'{_tspans(lines, bx + 60, first_baseline, lab_lh)}</text>'
        )
        by += bh + bgap

    # ── Report "paper" + phone, drawn LAST so the phone overlaps the boxes ────
    # Report page: gently tilted (~10 deg, a touch more upright than before),
    # top toward the upper right, fully inside the canvas.
    pa_w, pa_h = 206, 292
    pa_cx, pa_cy, pa_angle = 838, 248, 10
    parts.append(
        f'<g transform="rotate({pa_angle} {pa_cx} {pa_cy})" filter="url(#shadow)">'
        f'<rect x="{pa_cx - pa_w/2:.1f}" y="{pa_cy - pa_h/2:.1f}" width="{pa_w}" '
        f'height="{pa_h}" rx="6" ry="6" fill="#ffffff"/>'
        f'<image x="{pa_cx - pa_w/2:.1f}" y="{pa_cy - pa_h/2:.1f}" width="{pa_w}" '
        f'height="{pa_h}" preserveAspectRatio="xMidYMid slice" '
        f'xlink:href="{report_uri}"/>'
        f'</g>'
    )

    # GPLv3 logo (bottom-right corner): drawn HERE, AFTER the report "paper", so it
    # OVERLAPS/covers the tilted PDF screenshot instead of being hidden behind it.
    # Recoloured WHITE and right-anchored at the mirrored 48 px margin, sharing the
    # bottom baseline and visible height with the bottom-left badge. Its left edge
    # (x≈880) clears the phone + soft shadow (≈823), so being placed before the
    # phone below is fine — they do not overlap.
    parts.append(_logo_nested(W - margin - logo_w, baseline_y, logo_w, color="#ffffff"))

    # Right-side depth edge: a thin perspective band along the phone's NEAR (right)
    # edge, giving it visible thickness (the front face is otherwise flat). It is
    # tapered (shorter at the back) and drawn just before the phone so the front
    # face sits flush in front of it.
    rim_x = ph_x + ph_w
    rim_top, rim_bot = ph_y + ph_r, ph_y + ph_h - ph_r
    rim_d, rim_t = 9, 7
    parts.append(
        f'<polygon points="{rim_x},{rim_top} {rim_x + rim_d},{rim_top + rim_t} '
        f'{rim_x + rim_d},{rim_bot - rim_t} {rim_x},{rim_bot}" '
        f'fill="url(#edge)" filter="url(#shadow)"/>'
    )

    # Phone: built upright (bezel + screenshot + island) and perspective-warped to
    # lean back, all in Pillow; embedded here as ONE image. Its content is a
    # trapezoid inside the ph_w x ph_h box (transparent margins), and the image
    # already has those proportions, so it is placed with preserveAspectRatio
    # "none". The drop shadow follows the warped (trapezoidal) alpha.
    phone_uri = "data:image/png;base64," + base64.b64encode(
        _render_phone_png(today_png, ph_w, ph_h, ph_r, bezel)
    ).decode("ascii")
    parts.append(
        f'<image x="{ph_x}" y="{ph_y}" width="{ph_w}" height="{ph_h}" '
        f'preserveAspectRatio="none" filter="url(#shadow)" '
        f'xlink:href="{phone_uri}"/>'
    )

    parts.append("</svg>")
    return "".join(parts)


# ── Rendering ────────────────────────────────────────────────────────────────
def _render_png(svg: str, out_png: Path, scale: int = 1) -> None:
    """Render the SVG to a PNG with rsvg-convert using ONLY the bundled fonts.

    The output is `scale` x the Play feature-graphic size, i.e.
    (1024*scale) x (500*scale) px. The viewBox is unchanged, so the whole graphic
    is simply rasterised at a higher pixel density: vector elements (text, the
    badge and its fonts, the logo, shapes) stay razor-sharp, and the embedded
    screenshots -- heavily downscaled even at scale=4 -- stay crisp too.

    Determinism hinges on the font: librsvg resolves font families through
    fontconfig, so we generate a throwaway fontconfig that exposes ONLY
    tools/fonts/ and point FONTCONFIG_FILE at it. The host's installed
    fonts are therefore irrelevant -- the same Inter files are always used.
    """
    with tempfile.TemporaryDirectory() as td:
        tdp = Path(td)
        svg_path = tdp / "feature.svg"
        svg_path.write_text(svg, encoding="utf-8")

        fc_cache = tdp / "fc-cache"
        fc_cache.mkdir()
        fc_conf = tdp / "fonts.conf"
        fc_conf.write_text(
            "<?xml version='1.0'?>"
            "<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>"
            "<fontconfig>"
            f"<dir>{FONT_DIR}</dir>"
            f"<cachedir>{fc_cache}</cachedir>"
            "</fontconfig>",
            encoding="utf-8",
        )
        env = dict(os.environ)
        env["FONTCONFIG_FILE"] = str(fc_conf)

        out_png.parent.mkdir(parents=True, exist_ok=True)
        subprocess.run(
            [
                "rsvg-convert",
                "--width", str(W * scale),
                "--height", str(H * scale),
                "--format", "png",
                "--output", str(out_png),
                str(svg_path),
            ],
            check=True,
            env=env,
        )


def render_locale(locale: str) -> tuple[Path, Path]:
    """Render the feature graphic for one locale.

    Returns ``(store_png, hq_png)``: the 1024x500 Play graphic and its
    high-resolution companion.
    """
    loc_dir = META_DIR / locale
    copy = Copy.load(loc_dir / "feature-graphic.txt")
    shots = loc_dir / "images" / "phoneScreenshots"
    today_png = shots / "01_today.png"
    report_png = shots / "07_report_page_1.png"
    badge_svg = _badge_for_locale(locale)
    cjk_family = _cjk_family_for_locale(locale)
    for p in (today_png, report_png, ICON_FG, badge_svg):
        if not p.is_file():
            raise FileNotFoundError(f"required input missing: {p}")
    svg = _build_svg(copy, today_png, report_png, badge_svg, cjk_family)
    images = loc_dir / "images"
    out_png = images / "featureGraphic.png"
    _render_png(svg, out_png)                       # 1024x500, uploaded to Play
    # High-resolution companion for press/web/print. fastlane supply only matches
    # the exact name featureGraphic.png, so this file is never uploaded (and Play
    # caps the store feature graphic at 1024x500 anyway).
    hq_png = images / "featureGraphic-4K.png"
    _render_png(svg, hq_png, scale=HQ_SCALE)
    return out_png, hq_png


def main(argv: list[str]) -> int:
    """CLI entry point: render the feature graphic for the requested locales."""
    ap = argparse.ArgumentParser(
        description="Render Play-Store feature graphics deterministically."
    )
    ap.add_argument(
        "locales",
        nargs="*",
        help="locale dirs under fastlane/metadata/android/ "
        "(default: every locale that has a feature-graphic.txt)",
    )
    ap.add_argument(
        "--svg-only",
        metavar="FILE",
        help="write the assembled SVG for the FIRST locale to FILE and skip "
        "rendering (useful for inspecting/debugging the markup)",
    )
    args = ap.parse_args(argv)

    if shutil.which("rsvg-convert") is None:
        print(
            "render-feature-graphic: 'rsvg-convert' not found -- install it "
            "(Debian: apt install librsvg2-bin).",
            file=sys.stderr,
        )
        return 1

    locales = args.locales or sorted(
        p.parent.name
        for p in META_DIR.glob("*/feature-graphic.txt")
    )
    if not locales:
        print("render-feature-graphic: no feature-graphic.txt files found.",
              file=sys.stderr)
        return 1

    if args.svg_only:
        loc = locales[0]
        loc_dir = META_DIR / loc
        copy = Copy.load(loc_dir / "feature-graphic.txt")
        shots = loc_dir / "images" / "phoneScreenshots"
        svg = _build_svg(copy, shots / "01_today.png", shots / "07_report_page_1.png",
                         _badge_for_locale(loc), _cjk_family_for_locale(loc))
        Path(args.svg_only).write_text(svg, encoding="utf-8")
        print(f"wrote SVG for {loc} -> {args.svg_only}")
        return 0

    for loc in locales:
        out, hq = render_locale(loc)
        print(f"feature graphic ({loc}) -> {out}")
        print(f"  high-res     ({loc}) -> {hq}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
