#!/usr/bin/env python3
# vim: set et ts=4 sw=4:
# =============================================================================
# Libellus Potionis - Privacy-Friendly Alcohol Tracker
# Copyright (c) 2026 Martin A. Godisch <martin@godisch.de>
# =============================================================================
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <https://www.gnu.org/licenses/>.
#
# In addition, as permitted by section 7 of the GNU General Public License,
# this program may carry additional permissions; any such permissions that
# apply to it are stated in the accompanying COPYING.md file.
# =============================================================================

"""
render-bestpractices-jsonc.py -- annotate the badge answers with their level.

WHAT IT PRODUCES
    Reads the committed, machine-clean .bestpractices.json (a plain JSON object
    of <criterion>_status / <criterion>_justification pairs) and writes
    .bestpractices.jsonc, a HUMAN-oriented sibling in JSONC (JSON-with-comments)
    form. Immediately before each criterion's line it inserts a `//` comment
    naming the badge level on bestpractices.dev where that criterion is found:

        // OSPS Baseline -> level 1
        "OSPS-AC-01.01_justification": "...",
        // OSPS Baseline -> level 1
        "OSPS-AC-01.01_status": "Met",
        // Best Practices Badge (metal) -> passing
        "crypto_random_status": "Met",

    so a reader can open the right page (the metal `passing`/`silver`/`gold`
    tab, or the Baseline `level 1|2|3` view) to see the official criterion text
    beside the project's answer.

WHY A SEPARATE .jsonc AND NOT COMMENTS IN THE .json
    .bestpractices.json must stay valid JSON: it is consumed by tooling and is
    the artifact the badge workflow deals with. Comments would make it
    unparseable. The .jsonc is a generated, read-only VIEW; JSONC is understood
    by common editors (VS Code et al.) for syntax highlighting while remaining
    obviously non-canonical.

WHERE THE LEVELS COME FROM
    tools/bestpractices-levels.json -- an embedded, provenance-documented map
    (`metal` and `baseline` sections) regenerated by hand from the two
    upstream machine-readable sources. This script does NOT hit the network;
    the map is the single source of truth and check-bestpractices-levels.py
    guards it against drift from the answers file.

USAGE
    tools/render-bestpractices-jsonc.py [INPUT.json [OUTPUT.jsonc]]
    Defaults: .bestpractices.json -> .bestpractices.jsonc
    Exit status: 0 on success, 1 if a criterion has no level in the map
    (fail loud rather than emit a mislabelled line).
"""

import json
import os
import re
import sys

from potillus_repo import repo_root

ROOT = str(repo_root())
LEVELS_PATH = os.path.join(ROOT, "tools", "bestpractices-levels.json")

# A key is "<criterion>_status" or "<criterion>_justification"; strip the suffix
# to recover the criterion name that the level maps are keyed by.
_SUFFIX = re.compile(r"_(status|justification)$")


def criterion_of(key):
    """The bare criterion name behind a `_status` / `_justification` key."""
    return _SUFFIX.sub("", key)


def level_comment(criterion, levels):
    """The `//` annotation for one criterion, or None if it is unmapped."""
    if criterion.startswith("OSPS-"):
        level = levels["baseline"].get(criterion)
        return f"// OSPS Baseline -> {level}" if level else None
    level = levels["metal"].get(criterion)
    return f"// Best Practices Badge (metal) -> {level}" if level else None


def main(argv):
    in_path = argv[1] if len(argv) > 1 else os.path.join(ROOT, ".bestpractices.json")
    out_path = argv[2] if len(argv) > 2 else os.path.join(ROOT, ".bestpractices.jsonc")

    with open(in_path, encoding="utf-8") as handle:
        data = json.load(handle)
    with open(LEVELS_PATH, encoding="utf-8") as handle:
        levels = json.load(handle)

    # Serialize the object, then walk it line by line. Every criterion line is a
    # top-level `"<key>": ...` at two-space indent; we look each up and inject a
    # comment line ahead of it. Re-serializing (rather than string-editing the
    # input) guarantees the .jsonc payload is byte-for-byte the same JSON the
    # consumers see, only with comments interleaved.
    body = json.dumps(data, indent=2, ensure_ascii=False)

    key_line = re.compile(r'^  "(?P<key>[^"]+)":')
    out_lines = [
        "// ==========================================================================",
        "// .bestpractices.jsonc -- GENERATED, DO NOT EDIT.",
        "// A human-readable view of .bestpractices.json: each criterion is preceded",
        "// by a comment naming the bestpractices.dev level where it is found.",
        "// Regenerate with 'make bestpractices-jsonc'. Levels come from",
        "// tools/bestpractices-levels.json; see that file for provenance and URLs.",
        "// ==========================================================================",
    ]
    missing = []
    for line in body.split("\n"):
        match = key_line.match(line)
        if match:
            criterion = criterion_of(match.group("key"))
            comment = level_comment(criterion, levels)
            if comment is None:
                missing.append(criterion)
            else:
                out_lines.append("  " + comment)
        out_lines.append(line)

    if missing:
        unique = sorted(set(missing))
        for criterion in unique:
            print(
                f"render-bestpractices-jsonc: no level for '{criterion}' in "
                f"tools/bestpractices-levels.json",
                file=sys.stderr,
            )
        print(
            f"render-bestpractices-jsonc: {len(unique)} unmapped criterion(s); "
            f"update the map and retry",
            file=sys.stderr,
        )
        return 1

    with open(out_path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(out_lines) + "\n")
    print(
        f"render-bestpractices-jsonc: wrote {os.path.relpath(out_path, ROOT)} "
        f"({len(data)} keys annotated)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
